package br.com.bradseg.depi.depositoidentificado.model.enumerated;

/**
 * Enum de paises
 * 
 * @author CPM Braxis Capgemini em 17 de ago de 2017
 */
public enum PaisEnum {
	
	BR("BR","Brasil"),
	AF("AF","Afeganist�o"),
	ZA("ZA","�frica do Sul"),
	OR("OR","Alaranjado"),
	AL("AL","Alb�nia"),
	DE("DE","Alemanha"),
	AD("AD","Andorra"),
	AO("AO","Angola"),
	AI("AI","Anguilla"),
	AQ("AQ","Ant�rtica"),
	AG("AG","Ant�gua e Barbuda"),
	SA("SA","Ar�bia Saudita"),
	DZ("DZ","Arg�lia"),
	AR("AR","Argentina"),
	AM("AM","Arm�nia"),
	AW("AW","Aruba"),
	AU("AU","Austr�lia"),
	AT("AT","�ustria"),
	AZ("AZ","Azerbaij�o"),
	BL("BL","Azul"),
	BS("BS","Bahamas"),
	BD("BD","Bangladesh"),
	BB("BB","Barbados"),
	BH("BH","Barein"),
	BE("BE","B�lgica"),
	BZ("BZ","Belize"),
	BJ("BJ","Benin"),
	BM("BM","Bermudas"),
	BY("BY","Bielorr�ssia"),
	BO("BO","Bol�via"),
	BQ("BQ","Bonaire, Santo Eust�quio e Saba"),
	BA("BA","B�snia-Herzeg�vina"),
	BW("BW","Botsuana"),
	BN("BN","Brunei Darussalam"),
	BG("BG","Bulg�ria"),
	BF("BF","Burquina Faso"),
	BI("BI","Burundi"),
	BT("BT","But�o"),
	CV("CV","Cabo Verde"),
	CM("CM","Camar�es"),
	KH("KH","Camboja"),
	CA("CA","Canad�"),
	QA("QA","Catar"),
	KZ("KZ","Cazaquist�o"),
	TD("TD","Chade"),
	CL("CL","Chile"),
	CN("CN","China"),
	CY("CY","Chipre"),
	SG("SG","Cingapura"),
	CO("CO","Col�mbia"),
	KM("KM","Comores"),
	CG("CG","Congo"),
	KP("KP","Cor�ia do Norte"),
	KR("KR","Cor�ia do Sul"),
	CI("CI","Costa do Marfim"),
	CR("CR","Costa Rica"),
	HR("HR","Cro�cia"),
	CU("CU","Cuba"),
	CW("CW","Cura�ao"),
	DK("DK","Dinamarca"),
	DJ("DJ","Djibuti"),
	DM("DM","Dominica"),
	EG("EG","Egito"),
	SV("SV","El Salvador"),
	AE("AE","Emirados �rabes Unidos"),
	EC("EC","Equador"),
	ER("ER","Eritr�ia"),
	SK("SK","Eslov�quia"),
	SI("SI","Eslov�nia"),
	ES("ES","Espanha"),
	EE("EE","Est�nia"),
	ET("ET","Eti�pia"),
	US("US","EUA"),
	RU("RU","Federação Russa"),
	FJ("FJ","Fiji"),
	PH("PH","Filipinas"),
	FI("FI","Finl�ndia"),
	FR("FR","Fran�a"),
	GA("GA","Gab�o"),
	GM("GM","G�mbia"),
	GH("GH","Gana"),
	GE("GE","Ge�rgia"),
	GS("GS","Georgia do Sul e Ilhas Sandwich do Sul"),
	GI("GI","Gibraltar"),
	GD("GD","Granada"),
	GR("GR","Gr�cia"),
	GL("GL","Groenl�ndia"),
	GP("GP","Guadalupe"),
	GU("GU","Guam"),
	GT("GT","Guatemala"),
	GG("GG","Guernsey (ilha do Canal)"),
	GY("GY","Guiana"),
	GF("GF","Guiana francesa"),
	GN("GN","Guin�"),
	GW("GW","Guin� Bissau"),
	GQ("GQ","Guin� Equatorial"),
	HT("HT","Haiti"),
	HM("HM","Heard e Ilhas McDonald"),
	HN("HN","Honduras"),
	HK("HK","Hong Kong"),
	HU("HU","Hungria"),
	YE("YE","I�men"),
	CX("CX","Ilha Christmas"),
	CK("CK","Ilha Cook"),
	IM("IM","Ilha de Man"),
	NF("NF","Ilha Norfolk"),
	PN("PN","Ilha Pitcairn"),
	BV("BV","Ilhas Bouvet"),
	KY("KY","Ilhas Cayman"),
	CC("CC","Ilhas Coco"),
	FO("FO","Ilhas Faro�"),
	FK("FK","Ilhas Malvinas"),
	MH("MH","Ilhas Marshall"),
	UM("UM","Ilhas Menores dos EUA"),
	SB("SB","Ilhas Salom�o"),
	TK("TK","Ilhas Toquelau"),
	TC("TC","Ilhas Turcas e Caicos"),
	VG("VG","Ilhas Virgens (Reino Unido)"),
	VI("VI","Ilhas Virgens Americanas"),
	IN("IN","�ndia"),
	ID("ID","Indon�sia"),
	IR("IR","Ir�"),
	IQ("IQ","Iraque"),
	IE("IE","Irlanda"),
	IS("IS","Isl�ndia"),
	IL("IL","Israel"),
	IT("IT","It�lia"),
	JM("JM","Jamaica"),
	JP("JP","Jap�o"),
	JE("JE","J�rsei"),
	JO("JO","Jord�nia"),
	KI("KI","Kiribati"),
	KW("KW","Kuaite"),
	LA("LA","Laos"),
	LS("LS","Lesoto"),
	LV("LV","Let�nia"),
	LB("LB","L�bano"),
	LR("LR","Lib�ria"),
	LY("LY","L�bia"),
	LI("LI","Liechtenstein"),
	LT("LT","Litu�nia"),
	LU("LU","Luxemburgo"),
	MO("MO","Macau"),
	MK("MK","Maced�nia"),
	MG("MG","Madagascar"),
	MY("MY","Mal�sia"),
	MW("MW","Mal�wi"),
	MV("MV","Maldivas"),
	ML("ML","Mali"),
	MT("MT","Malta"),
	MP("MP","Marianas do Norte"),
	MA("MA","Marrocos"),
	MQ("MQ","Martinica"),
	MU("MU","Maur�cio"),
	MR("MR","Maurit�nia"),
	YT("YT","Mayotte"),
	MX("MX","M�xico"),
	FM("FM","Micron�sia"),
	MZ("MZ","Mo�ambique"),
	MD("MD","Moldova"),
	MC("MC","M�naco"),
	MN("MN","Mong�lia"),
	MS("MS","Montserrat"),
	MM("MM","Myanmar"),
	UN("UN","Na��es Unidas"),
	NA("NA","Nam�bia"),
	NR("NR","Nauru"),
	NP("NP","Nepal"),
	NI("NI","Nicar�gua"),
	NE("NE","N�ger"),
	NG("NG","Nig�ria"),
	NU("NU","Niue"),
	NO("NO","Noruega"),
	NC("NC","Nova Caled�nia"),
	NZ("NZ","Nova Zel�ndia"),
	OM("OM","Om�"),
	NT("NT","OTAN"),
	NL("NL","Pa�ses Baixos"),
	PW("PW","Palau"),
	PS("PS","Palestina"),
	PA("PA","Panam�"),
	PG("PG","Papua Nova Guin�"),
	PK("PK","Paquist�o"),
	PY("PY","Paraguai"),
	PE("PE","Peru"),
	PF("PF","Polin�sia Francesa"),
	PL("PL","Pol�nia"),
	PR("PR","Porto Rico"),
	PT("PT","Portugal"),
	KE("KE","Qu�nia"),
	KG("KG","Quirguist�o"),
	GB("GB","Reino Unido"),
	CF("CF","Rep�blica Centro-Africana"),
	CD("CD","Rep�blica do Congo"),
	DO("DO","Rep�blica Dominicana"),
	CZ("CZ","Rep�blica Tcheca"),
	RE("RE","Reuni�o"),
	RO("RO","Rom�nia"),
	RW("RW","Ruanda"),
	EH("EH","Saara Ocidental"),
	AS("AS","Samoa Americana"),
	WS("WS","Samoa Ocidental"),
	SM("SM","San Marino"),
	SH("SH","Santa Helena"),
	LC("LC","Santa L�cia"),
	KN("KN","S�o Crist�v�o e N�vis"),
	SX("SX","S�o Martinho (parte neerlandesa)"),
	PM("PM","S�o Pedro e Miquelon"),
	ST("ST","S�o Tom� e Pr�ncipe"),
	VC("VC","S�o Vicente e Granadinas"),
	SC("SC","Seicheles"),
	SN("SN","Senegal"),
	SL("SL","Serra Leoa"),
	CS("CS","S�rvia e Montenegro"),
	SY("SY","S�ria"),
	SO("SO","Som�lia"),
	LK("LK","Sri Lanka"),
	SZ("SZ","Suazilandia"),
	SD("SD","Sud�o"),
	SS("SS","Sud�o do Sul"),
	SE("SE","Su�cia"),
	CH("CH","Su��a"),
	SR("SR","Suriname"),
	SJ("SJ","Svalbard"),
	TJ("TJ","Tadjiquist�o"),
	TH("TH","Tail�ndia"),
	TW("TW","Taiwan"),
	TZ("TZ","Tanz�nia"),
	TF("TF","Terras Austrais e Ant�rticas Francesas"),
	IO("IO","Territ�rio Brit�nico no Oceano �ndico"),
	TL("TL","Timor Leste"),
	TP("TP","Timor Leste"),
	TG("TG","Togo"),
	TO("TO","Tonga"),
	TT("TT","Trinidad e Tobago"),
	TN("TN","Tun�sia"),
	TM("TM","Turcomenist�o"),
	TR("TR","Turquia"),
	TV("TV","Tuvalu"),
	UA("UA","Ucr�nia"),
	UG("UG","Uganda"),
	EU("EU","Uni�o Europ�ia"),
	UY("UY","Uruguai"),
	UZ("UZ","Uzbequist�o"),
	VU("VU","Vanuato"),
	VA("VA","Vaticano"),
	VE("VE","Venezuela"),
	VN("VN","Vietn�"),
	WF("WF","Wallis e Futuna"),
	ZM("ZM","Z�mbia"),
	ZW("ZW","Zimb�bue"),
	AX("AX","AX"),
	ME("ME","ME"),
	MF("MF","MF"),
	RS("RS","RS");

	private String codigo;
	private String descricao;

	PaisEnum(String codigo, String descricao) {
		this.codigo = codigo;
		this.descricao = descricao;
	}

	/**
	 * Retorna o atributo codigo.
	 * 
	 * @return Retorna o atributo codigo do tipo String.
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * Especifica o atributo codigo.
	 * 
	 * @param codigo String referente a codigo a ser setado.
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * Retorna o atributo descricao.
	 * 
	 * @return Retorna o atributo descricao do tipo String.
	 */
	public String getDescricao() {
		return descricao;
	}

	/**
	 * Especifica o atributo descricao.
	 * 
	 * @param descricao String referente a descricao a ser setado.
	 */
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
