package br.com.bradseg.depi.depositoidentificado.util;

/**
 * A(O) Class Querys.
 */
public class QuerysDepi {

	private static final String CAMPOS_SELECT_DEPARTAMENTO = "SELECT DISTINCT D.IDEPTO_DEP_IDTFD, D.DHORA_ULT_ATULZ, D.DHORA_INCL_REG, D.CUSUAR_RESP_ATULZ, D.CSGL_DEPTO_DEP, D.CIND_REG_ATIVO, D.CDEPTO_DEP_IDTFD ";

	public static final String ASSOCIARMOTIVODEPOSITO_INSERT = "INSERT INTO DBPROD.CTA_CORR_MOTVO_DEP (CINTRN_CIA_SEGDR, CDEPTO_DEP_IDTFD, CMOTVO_DEP_IDTFD, CBCO, CAG_BCRIA, CCTA_CORR, CUSUAR_RESP_ATULZ, DHORA_INCL_REG, DHORA_ULT_ATULZ, CIND_REG_ATIVO) " + 
			"VALUES (:prm1, :prm2, :prm3, :prm4, :prm5, :prm6, :prm7, CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'S')";

	public static final String ASSOCIARMOTIVODEPOSITO_EXISTS = "SELECT CIND_REG_ATIVO FROM DBPROD.CTA_CORR_MOTVO_DEP " +
			"WHERE CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = :whr3 AND CBCO = :whr4 AND CAG_BCRIA = :whr5 AND CCTA_CORR  = :whr6"; 

	public static final String ASSOCIARMOTIVODEPOSITO_INATIVAR = "UPDATE DBPROD.CTA_CORR_MOTVO_DEP SET CIND_REG_ATIVO = 'N', DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm1 " +
			"WHERE CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = :whr3 AND CBCO = :whr4 AND CAG_BCRIA = :whr5 AND CCTA_CORR  = :whr6";

	public static final String ASSOCIARMOTIVODEPOSITO_REATIVAR = "UPDATE DBPROD.CTA_CORR_MOTVO_DEP SET CIND_REG_ATIVO = 'S', DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm1 " +
			"WHERE CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = :whr3 AND CBCO = whr4 AND CAG_BCRIA = whr5 AND CCTA_CORR = :whr6";

	public static final String ASSOCIARMOTIVODEPOSITO_REFERENCIADO_DEPOSITO = "SELECT 1 FROM DBPROD.DEP_IDTFD WHERE CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = :whr3 AND CBCO = :whr4 AND CAG_BCRIA = :whr5 AND CCTA_CORR = :whr6 AND CIND_REG_ATIVO = 'S'";
	
	public static final String ASSOCIARMOTIVODEPOSITO_OBTERPORFILTRO = "SELECT DBPROD.CTA_CORR_MOTVO_DEP.CINTRN_CIA_SEGDR, DBPROD.CTA_CORR_MOTVO_DEP.CDEPTO_DEP_IDTFD, DBPROD.CTA_CORR_MOTVO_DEP.CMOTVO_DEP_IDTFD, " +
				"DBPROD.CTA_CORR_MOTVO_DEP.CBCO, DBPROD.CTA_CORR_MOTVO_DEP.CAG_BCRIA, DBPROD.CTA_CORR_MOTVO_DEP.CCTA_CORR, DBPROD.CTA_CORR_MOTVO_DEP.DHORA_INCL_REG, DBPROD.CTA_CORR_MOTVO_DEP.DHORA_ULT_ATULZ, " +
				"DBPROD.CTA_CORR_MOTVO_DEP.CUSUAR_RESP_ATULZ, DBPROD.CTA_CORR_MOTVO_DEP.CIND_REG_ATIVO FROM DBPROD.CTA_CORR_MOTVO_DEP, DBPROD.DEPTO_DEP_IDTFD, DBPROD.MOTVO_DEP_IDTFD WHERE DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD = DBPROD.CTA_CORR_MOTVO_DEP.CDEPTO_DEP_IDTFD " +
				"AND DBPROD.MOTVO_DEP_IDTFD.CMOTVO_DEP_IDTFD = DBPROD.CTA_CORR_MOTVO_DEP.CMOTVO_DEP_IDTFD AND DBPROD.CTA_CORR_MOTVO_DEP.CIND_REG_ATIVO = 'S' {0}  ORDER BY DBPROD.CTA_CORR_MOTVO_DEP.DHORA_ULT_ATULZ ASC";
	
	public static final String ASSOCIARMOTIVODEPOSITO_OBTERPORFILTROCOMRESTRICAODEGRUPOACESSO= "SELECT DBPROD.CTA_CORR_MOTVO_DEP.CINTRN_CIA_SEGDR, DBPROD.CTA_CORR_MOTVO_DEP.CDEPTO_DEP_IDTFD, DBPROD.CTA_CORR_MOTVO_DEP.CMOTVO_DEP_IDTFD, DBPROD.CTA_CORR_MOTVO_DEP.CBCO, DBPROD.CTA_CORR_MOTVO_DEP.CAG_BCRIA, DBPROD.CTA_CORR_MOTVO_DEP.CCTA_CORR, DBPROD.CTA_CORR_MOTVO_DEP.DHORA_INCL_REG, DBPROD.CTA_CORR_MOTVO_DEP.DHORA_ULT_ATULZ, DBPROD.CTA_CORR_MOTVO_DEP.CUSUAR_RESP_ATULZ, DBPROD.CTA_CORR_MOTVO_DEP.CIND_REG_ATIVO, DBPROD.DEPTO_DEP_IDTFD.CSGL_DEPTO_DEP " + 
            "FROM DBPROD.CTA_CORR_MOTVO_DEP, DBPROD.GRP_DEPTO_DEP, DBPROD.ALOC_USUAR_GRP_DEP, DBPROD.MOTVO_DEP_IDTFD, DBPROD.DEPTO_DEP_IDTFD " +
            "WHERE DBPROD.GRP_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.CTA_CORR_MOTVO_DEP.CDEPTO_DEP_IDTFD AND 	DBPROD.GRP_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.CTA_CORR_MOTVO_DEP.CINTRN_CIA_SEGDR " +
			"AND DBPROD.ALOC_USUAR_GRP_DEP.CGRP_DEPTO_DEP = DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP AND DBPROD.CTA_CORR_MOTVO_DEP.CMOTVO_DEP_IDTFD = DBPROD.MOTVO_DEP_IDTFD.CMOTVO_DEP_IDTFD " +
			"AND DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD = DBPROD.CTA_CORR_MOTVO_DEP.CDEPTO_DEP_IDTFD AND 	DBPROD.GRP_DEPTO_DEP.CIND_REG_ATIVO = 'S' " +
			"AND DBPROD.ALOC_USUAR_GRP_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.CTA_CORR_MOTVO_DEP.CIND_REG_ATIVO = 'S' " + 
			"AND DBPROD.MOTVO_DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.DEPTO_DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.ALOC_USUAR_GRP_DEP.CUSUAR_DEP_IDTFD = :whr1 " + 
			"{0}  ORDER BY DBPROD.CTA_CORR_MOTVO_DEP.DHORA_ULT_ATULZ DESC";
	
	public static final String ASSOCIARMOTIVODEPOSITO_OBTERPORCHAVE = "SELECT DBPROD.CTA_CORR_MOTVO_DEP.CINTRN_CIA_SEGDR, DBPROD.CTA_CORR_MOTVO_DEP.CDEPTO_DEP_IDTFD, DBPROD.CTA_CORR_MOTVO_DEP.CMOTVO_DEP_IDTFD, DBPROD.CTA_CORR_MOTVO_DEP.CBCO, DBPROD.CTA_CORR_MOTVO_DEP.CAG_BCRIA, DBPROD.CTA_CORR_MOTVO_DEP.CCTA_CORR, DBPROD.CTA_CORR_MOTVO_DEP.DHORA_INCL_REG, DBPROD.CTA_CORR_MOTVO_DEP.DHORA_ULT_ATULZ, DBPROD.CTA_CORR_MOTVO_DEP.CUSUAR_RESP_ATULZ, DBPROD.CTA_CORR_MOTVO_DEP.CIND_REG_ATIVO " +
			"FROM DBPROD.CTA_CORR_MOTVO_DEP, DBPROD.DEPTO_DEP_IDTFD, DBPROD.MOTVO_DEP_IDTFD " +
			"WHERE DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD = DBPROD.CTA_CORR_MOTVO_DEP.CDEPTO_DEP_IDTFD " +
			"AND DBPROD.MOTVO_DEP_IDTFD.CMOTVO_DEP_IDTFD = DBPROD.CTA_CORR_MOTVO_DEP.CMOTVO_DEP_IDTFD " + 
			"AND DBPROD.CTA_CORR_MOTVO_DEP.CIND_REG_ATIVO = 'S' AND  DBPROD.CTA_CORR_MOTVO_DEP.CAG_BCRIA = :whr1 " + 
			"AND DBPROD.CTA_CORR_MOTVO_DEP.CBCO = :whr2 " + 
			"AND DBPROD.CTA_CORR_MOTVO_DEP.CCTA_CORR = :whr3 " + 
			"AND DBPROD.CTA_CORR_MOTVO_DEP.CDEPTO_DEP_IDTFD = :whr4 " + 
			"AND DBPROD.CTA_CORR_MOTVO_DEP.CINTRN_CIA_SEGDR = :whr5 " + 
			"AND DBPROD.CTA_CORR_MOTVO_DEP.CMOTVO_DEP_IDTFD = :whr6  ORDER BY DBPROD.CTA_CORR_MOTVO_DEP.DHORA_ULT_ATULZ ASC";

	
	public static final String  CONTACORRENTEAUTORIZADA_INSERT = "INSERT INTO DBPROD.CTA_CORR_AUTRZ  (CBCO, CAG_BCRIA, CCTA_CORR, CINTRN_CIA_SEGDR, CCTA_CORR_AUTRZ, CDIG_AG, CPRIM_DIG_CTA, " +
			"CSEGDA_DIG_CTA, ROBS_CTA_AUTRZ, DHORA_INCL_REG, DHORA_ULT_ATULZ, CIND_REG_ATIVO, CUSUAR_RESP_ATULZ, NCLI_TRANS_PERSO) "+
			"VALUES (:prm1, :prm2, :prm3, :prm4, :prm5, :prm6, :prm7, :prm8, :prm9, CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'S', :prm10, :prm11)";

	public static final String CONTACORRENTEAUTORIZADA_REATIVAR = "UPDATE DBPROD.CTA_CORR_AUTRZ SET CIND_REG_ATIVO = 'S', DHORA_ULT_ATULZ = CURRENT TIMESTAMP, ROBS_CTA_AUTRZ = :prm1, CUSUAR_RESP_ATULZ = prm2 WHERE CBCO = :whr1 AND CAG_BCRIA = :whr2 AND CCTA_CORR = :whr3";

	public static final String CONTACORRENTEAUTORIZADA_INATIVAR = "UPDATE DBPROD.CTA_CORR_AUTRZ SET CIND_REG_ATIVO = 'N', DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm1 WHERE CBCO = :whr1 AND CAG_BCRIA = :whr2 AND CCTA_CORR = :whr3";

	public static final String CONTACORRENTEAUTORIZADA_UPDATE = "UPDATE DBPROD.CTA_CORR_AUTRZ SET DHORA_ULT_ATULZ = CURRENT TIMESTAMP, ROBS_CTA_AUTRZ = :prm1, CUSUAR_RESP_ATULZ = :prm2 WHERE CBCO = :whr1 AND CAG_BCRIA = :whr2 AND CCTA_CORR = :whr3";

	public static final String CONTACORRENTEAUTORIZADA_OBTERBANCOSCOMRESTRICAODEASSOCIACAODEMOTIVOS = "SELECT DISTINCT CBCO FROM DBPROD.CTA_CORR_MOTVO_DEP WHERE CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = :whr3 AND CIND_REG_ATIVO = 'S' ORDER BY CBCO ASC";

	public static final String CONTACORRENTEAUTORIZADA_OBTERAGENCIASCOMRESTRICAODEASSOCIACAODEMOTIVOS = "SELECT DISTINCT CAG_BCRIA FROM DBPROD.CTA_CORR_MOTVO_DEP WHERE CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = :whr3 AND CBCO = :whr4 AND CIND_REG_ATIVO = 'S' ORDER BY CAG_BCRIA ASC";

	public static final String CONTACORRENTEAUTORIZADA_OBTERCONTACORRENTECOMRESTRICAODEASSOCIACAODEMOTIVOS = "SELECT DISTINCT CCM.CCTA_CORR, CCA.CCTA_CORR_AUTRZ, CCA.NCLI_TRANS_PERSO FROM DBPROD.CTA_CORR_MOTVO_DEP CCM, DBPROD.CTA_CORR_AUTRZ CCA " +
	         "WHERE CCM.CBCO = CCA.CBCO AND CCM.CAG_BCRIA = CCA.CAG_BCRIA AND CCM.CCTA_CORR = CCA.CCTA_CORR AND CCM.CINTRN_CIA_SEGDR = :whr1 AND CCM.CDEPTO_DEP_IDTFD = :whr2 AND CCM.CMOTVO_DEP_IDTFD = :whr3 AND CCM.CBCO = :whr4 AND CCM.CAG_BCRIA = :whr5 AND CCM.CIND_REG_ATIVO = 'S' ORDER BY CCM.CCTA_CORR ASC";

	public static final String CONTACORRENTEAUTORIZADA_OBTERPORTRPS = "SELECT DISTINCT NCLI_TRANS_PERSO FROM DBPROD.CTA_CORR_AUTRZ WHERE NCLI_TRANS_PERSO = :whr1";

	public static final String CONTACORRENTEAUTORIZADA_OBTERBANCOS = "SELECT DISTINCT CBCO FROM DBPROD.CTA_CORR_AUTRZ WHERE CINTRN_CIA_SEGDR = :whr1 AND CIND_REG_ATIVO = 'S' ORDER BY CBCO ASC";

	public static final String CONTACORRENTEAUTORIZADA_OBTERAGENCIAS = "SELECT DISTINCT CBCO, CAG_BCRIA FROM DBPROD.CTA_CORR_AUTRZ WHERE CINTRN_CIA_SEGDR = :whr1 AND CBCO = :whr2 AND CIND_REG_ATIVO = 'S' ORDER BY CAG_BCRIA ASC";

	public static final String CONTACORRENTEAUTORIZADA_OBTERCONTAS = "SELECT DISTINCT CCTA_CORR, CCTA_CORR_AUTRZ FROM DBPROD.CTA_CORR_AUTRZ  WHERE CINTRN_CIA_SEGDR = :whr1 AND CBCO = :whr2 AND CAG_BCRIA = :whr3 AND CIND_REG_ATIVO = 'S' ORDER BY CCTA_CORR ASC";

	public static final String CONTACORRENTEAUTORIZADA_EXISTS = "SELECT CIND_REG_ATIVO FROM DBPROD.CTA_CORR_AUTRZ WHERE CBCO = :whr1 AND CAG_BCRIA = :whr2 AND CCTA_CORR = :whr3";

	public static final String CONTACORRENTEAUTORIZADA_REFERENCIADO_CONTACORRENTEMOTIVODEPOSITO = "SELECT CCMD.CINTRN_CIA_SEGDR, CCMD.CDEPTO_DEP_IDTFD, CCMD.CMOTVO_DEP_IDTFD, CCMD.CBCO, CCMD.CAG_BCRIA, " +
				"CCMD.CCTA_CORR, CCMD.DHORA_INCL_REG, CCMD.DHORA_ULT_ATULZ, CCMD.CUSUAR_RESP_ATULZ, CCMD.CIND_REG_ATIVO FROM DBPROD.CTA_CORR_MOTVO_DEP CCMD " + 
				"WHERE CCMD.CBCO = :whr1 AND CCMD.CAG_BCRIA = :whr2 AND CCMD.CCTA_CORR = :whr3 AND CCMD.CIND_REG_ATIVO = 'S'"; 

	public static final String CONTACORRENTEAUTORIZADA_OBTERPORFILTROCOMRESTRICAODEGRUPOACESSO= "SELECT DISTINCT DBPROD.CTA_CORR_AUTRZ.CBCO, DBPROD.CTA_CORR_AUTRZ.CAG_BCRIA, DBPROD.CTA_CORR_AUTRZ.CCTA_CORR, " +
			"DBPROD.CTA_CORR_AUTRZ.ROBS_CTA_AUTRZ, DBPROD.CTA_CORR_AUTRZ.DHORA_INCL_REG, DBPROD.CTA_CORR_AUTRZ.DHORA_ULT_ATULZ, DBPROD.CTA_CORR_AUTRZ.CCTA_CORR_AUTRZ, DBPROD.CTA_CORR_AUTRZ.CUSUAR_RESP_ATULZ, " +
			"DBPROD.CTA_CORR_AUTRZ.CIND_REG_ATIVO, DBPROD.CTA_CORR_AUTRZ.CDIG_AG, DBPROD.CTA_CORR_AUTRZ.CPRIM_DIG_CTA, DBPROD.CTA_CORR_AUTRZ.CSEGDA_DIG_CTA, DBPROD.CTA_CORR_AUTRZ.CINTRN_CIA_SEGDR, DBPROD.CTA_CORR_AUTRZ.NCLI_TRANS_PERSO " + 
			"FROM DBPROD.CTA_CORR_AUTRZ, DBPROD.GRP_DEPTO_DEP, DBPROD.ALOC_USUAR_GRP_DEP " + 
			"WHERE DBPROD.GRP_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.CTA_CORR_AUTRZ.CINTRN_CIA_SEGDR AND DBPROD.GRP_DEPTO_DEP.CIND_REG_ATIVO = 'S' " + 
			"AND DBPROD.ALOC_USUAR_GRP_DEP.CGRP_DEPTO_DEP = DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP AND	DBPROD.ALOC_USUAR_GRP_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.ALOC_USUAR_GRP_DEP.CUSUAR_DEP_IDTFD = :whr1 " +
			"AND DBPROD.CTA_CORR_AUTRZ.CIND_REG_ATIVO = 'S' {0}  ORDER BY DBPROD.CTA_CORR_AUTRZ.DHORA_ULT_ATULZ DESC" ; 

	public static final String DEPARTAMENTOCOMPANHIA_EXISTS = "SELECT CIND_REG_ATIVO FROM DBPROD.CIA_DEPTO_DEP WHERE CDEPTO_DEP_IDTFD = :whr1 AND CINTRN_CIA_SEGDR = :whr2";

	public static final String DEPARTAMENTOCOMPANHIA_REFERENCIADO_PARAMETRODEPOSITO = "SELECT 1 FROM DBPROD.PARMZ_DEP_IDTFD WHERE CIND_REG_ATIVO = 'S' AND CDEPTO_DEP_IDTFD = :whr1 AND CINTRN_CIA_SEGDR = :whr2"; 

	public static final String DEPARTAMENTOCOMPANHIA_REFERENCIADO_GRUPODEPARTAMENTO = "SELECT 1 FROM DBPROD.GRP_DEPTO_DEP WHERE CIND_REG_ATIVO = 'S' AND CDEPTO_DEP_IDTFD = :whr1 AND CINTRN_CIA_SEGDR = :whr2";

	public static final String DEPARTAMENTOCOMPANHIA_REFERENCIADO_CONTACORRENTEMOTIVODEPOSITO = "SELECT 1 FROM DBPROD.CTA_CORR_MOTVO_DEP WHERE CIND_REG_ATIVO = 'S' AND CINTRN_CIA_SEGDR = :whr1";

	public static final String DEPARTAMENTOCOMPANHIA_INSERT = "INSERT INTO DBPROD.CIA_DEPTO_DEP (CDEPTO_DEP_IDTFD, CINTRN_CIA_SEGDR, DHORA_INCL_REG, DHORA_ULT_ATULZ, CUSUAR_RESP_ATULZ, CIND_REG_ATIVO ) VALUES (:prm1, :prm2, CURRENT TIMESTAMP, CURRENT TIMESTAMP, :prm3, 'S')";

	public static final String DEPARTAMENTOCOMPANHIA_ATIVAR = "UPDATE DBPROD.CIA_DEPTO_DEP SET DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CIND_REG_ATIVO = 'S', CUSUAR_RESP_ATULZ = :prm1 WHERE CDEPTO_DEP_IDTFD = :whr1 AND CINTRN_CIA_SEGDR = :whr1";

	public static final String DEPARTAMENTOCOMPANHIA_INATIVAR = "UPDATE DBPROD.CIA_DEPTO_DEP SET CIND_REG_ATIVO = 'N', DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm1 WHERE CDEPTO_DEP_IDTFD = :whr1 AND CINTRN_CIA_SEGDR = :whr2 AND CIND_REG_ATIVO = 'S'"; 

	public static final String DEPARTAMENTOCOMPANHIA_DELETE = "DELETE FROM DBPROD.CIA_DEPTO_DEP WHERE DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = :whr1 AND DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO = 'N' AND DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = :whr2"; 

	public static final String DEPARTAMENTOCOMPANHIA_OBTERPORFILTRO = "SELECT CIA.CINTRN_CIA_SEGDR, CIA.CDEPTO_DEP_IDTFD, DEPTO.IDEPTO_DEP_IDTFD, DEPTO.CSGL_DEPTO_DEP, CIA.DHORA_INCL_REG, CIA.CUSUAR_RESP_ATULZ, CIA.DHORA_ULT_ATULZ, CIA.CIND_REG_ATIVO " + 
			"FROM DBPROD.CIA_DEPTO_DEP CIA, DBPROD.DEPTO_DEP_IDTFD DEPTO, DBPROD.COD_INTRN_CIA COD WHERE DEPTO.CDEPTO_DEP_IDTFD = CIA.CDEPTO_DEP_IDTFD AND DEPTO.CDEPTO_DEP_IDTFD = CIA.CDEPTO_DEP_IDTFD " +
			"AND CIA.CINTRN_CIA_SEGDR = COD.CINTRN_CIA_SEGDR AND CIA.CIND_REG_ATIVO = 'S' {0}  ORDER BY CIA.DHORA_ULT_ATULZ DESC"; 

	public static final String DEPARTAMENTOCOMPANHIA_OBTERCIAS = "SELECT DISTINCT DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR FROM   DBPROD.CIA_DEPTO_DEP, DBPROD.COD_INTRN_CIA " +
			"WHERE  DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR ORDER BY DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR ASC ";

	public static final String DEPARTAMENTOCOMPANHIA_OBTERPORCIA = "SELECT DC.CINTRN_CIA_SEGDR, DC.CDEPTO_DEP_IDTFD, DC.DHORA_INCL_REG, DC.CUSUAR_RESP_ATULZ, DC.DHORA_ULT_ATULZ, DC.CIND_REG_ATIVO, DEP.IDEPTO_DEP_IDTFD, DEP.CSGL_DEPTO_DEP FROM DBPROD.CIA_DEPTO_DEP DC, DBPROD.COD_INTRN_CIA CI, DBPROD.DEPTO_DEP_IDTFD DEP " + 
			"WHERE DC.CINTRN_CIA_SEGDR = :whr1 AND   DC.CINTRN_CIA_SEGDR = CI.CINTRN_CIA_SEGDR AND DC.CDEPTO_DEP_IDTFD = DEP.CDEPTO_DEP_IDTFD AND   DC.CIND_REG_ATIVO = 'S'";

	public static final String DEPARTAMENTOCOMPANHIA_OBTERPORCOMPANHIASEGURADORA2 = "SELECT DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD, DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR, DBPROD.CIA_DEPTO_DEP.DHORA_INCL_REG, " + 
			"DBPROD.CIA_DEPTO_DEP.DHORA_ULT_ATULZ, DBPROD.CIA_DEPTO_DEP.CUSUAR_RESP_ATULZ, DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO  " + 
			"FROM DBPROD.CIA_DEPTO_DEP, DBPROD.COD_INTRN_CIA, DBPROD.DEPTO_DEP_IDTFD WHERE DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD " + 
			"AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = :whr1 AND DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = :whr2 AND DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO = 'N' AND DBPROD.DEPTO_DEP_IDTFD.CIND_REG_ATIVO = 'N'";

	public static final String DEPARTAMENTOCOMPANHIA_OBTERPORCHAVE = "SELECT DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD, DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR, DBPROD.CIA_DEPTO_DEP.DHORA_INCL_REG, " +
			"DBPROD.CIA_DEPTO_DEP.DHORA_ULT_ATULZ, DBPROD.CIA_DEPTO_DEP.CUSUAR_RESP_ATULZ, DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO  " + 
			"FROM DBPROD.CIA_DEPTO_DEP, DBPROD.COD_INTRN_CIA " + 
			"WHERE DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO = 'N' AND DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = :whr1 AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = :whr2";

	public static final String DEPARTAMENTOCOMPANHIA_OBTERDEPARTAMENTOCOMPANHIAPORCHAVE = "SELECT CDEPTO_DEP_IDTFD, CIND_REG_ATIVO, CINTRN_CIA_SEGDR, CUSUAR_RESP_ATULZ, DHORA_INCL_REG, DHORA_ULT_ATULZ FROM DBPROD.CIA_DEPTO_DEP " + 
			"WHERE CDEPTO_DEP_IDTFD = :whr1 AND CINTRN_CIA_SEGDR = :whr2"; 
	
	public static final String DEPARTAMENTOCOMPANHIA_ISEXISTEASSOCIACAOPORFK = "SELECT DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD, DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR  FROM DBPROD.CIA_DEPTO_DEP, DBPROD.COD_INTRN_CIA " +
			"WHERE DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = :whr1 AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = :whr2 AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR AND DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO = 'N'";	

	public static final String DEPARTAMENTOCOMPANHIA_OBTERPORUSUARIO = "SELECT DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD, DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR, DBPROD.CIA_DEPTO_DEP.DHORA_INCL_REG, DBPROD.CIA_DEPTO_DEP.DHORA_ULT_ATULZ, DBPROD.CIA_DEPTO_DEP.CUSUAR_RESP_ATULZ, DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO, DBPROD.DEPTO_DEP_IDTFD.IDEPTO_DEP_IDTFD  " + 
			"FROM DBPROD.DEPTO_DEP_IDTFD, DBPROD.CIA_DEPTO_DEP, DBPROD.GRP_DEPTO_DEP, DBPROD.ALOC_USUAR_GRP_DEP, DBPROD.USUAR_DEP_IDTFD, DBPROD.COD_INTRN_CIA  " + 
			"WHERE DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD AND DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO = 'S'  AND DBPROD.DEPTO_CIA.CDEPTO_CIA = DBPROD.GRP_USUAR_DEPTO.CDEPTO_CIA " + 
			"AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR AND DBPROD.ALOC_USUAR_GRP_DEP.CGRP_DEPTO_DEP = DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP AND DBPROD.USUAR_DEP_IDTFD.CUSUAR_DEP_IDTFD = DBPROD.ALOC_USUAR_GRP_DEP.CUSUAR_DEP_IDTFD  AND DBPROD.USUAR.CUSUAR_DEP_IDTFD = :whr1 ORDER BY DHORA_ULT_ATULZ DESC";

	public static final String DEPARTAMENTOCOMPANHIA_OBTERSEQUENCIA = "SELECT DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD, DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR, DBPROD.CIA_DEPTO_DEP.DHORA_INCL_REG, DBPROD.CIA_DEPTO_DEP.DHORA_ULT_ATULZ, DBPROD.CIA_DEPTO_DEP.CUSUAR_RESP_ATULZ, DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO  " + 
			"FROM DBPROD.CIA_DEPTO_DEP, DBPROD.COD_INTRN_CIA  " + 
			"WHERE DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = :whr1 AND DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR AND DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = :whr2"; 

	public static final String DEPARTAMENTO_EXISTS= "SELECT CDEPTO_DEP_IDTFD, CSGL_DEPTO_DEP , CIND_REG_ATIVO, IDEPTO_DEP_IDTFD, CUSUAR_RESP_ATULZ FROM DBPROD.DEPTO_DEP_IDTFD WHERE CSGL_DEPTO_DEP = :whr1";

	public static final String DEPARTAMENTO_REFERENCIADO_COMPANHIADEPARTAMENTO = "SELECT 1 FROM DBPROD.CIA_DEPTO_DEP WHERE CIND_REG_ATIVO = 'S' AND CDEPTO_DEP_IDTFD = :whr1";

	public static final String DEPARTAMENTO_OBTERCOMRESTRICAODEGRUPOACESSO = CAMPOS_SELECT_DEPARTAMENTO + 
	        "FROM DBPROD.DEPTO_DEP_IDTFD D, DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A " +
			"WHERE D.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND G.CIND_REG_ATIVO = 'S' AND A.CGRP_DEPTO_DEP = G.CGRP_DEPTO_DEP AND G.CINTRN_CIA_SEGDR = :whr1 AND A.CUSUAR_DEP_IDTFD = :whr2 AND A.CIND_REG_ATIVO = 'S' ORDER BY D.CDEPTO_DEP_IDTFD ASC";

	public static final String DEPARTAMENTO_OBTERPORCHAVE = "SELECT DISTINCT D.IDEPTO_DEP_IDTFD, D.DHORA_ULT_ATULZ, D.DHORA_INCL_REG, D.CUSUAR_RESP_ATULZ, D.CSGL_DEPTO_DEP, D.CIND_REG_ATIVO, D.CDEPTO_DEP_IDTFD FROM DBPROD.DEPTO_DEP_IDTFD D WHERE D.CDEPTO_DEP_IDTFD = :whr1";
	
	public static final String DEPARTAMENTO_OBTERTODOS = "SELECT DISTINCT D.IDEPTO_DEP_IDTFD, D.DHORA_ULT_ATULZ, D.DHORA_INCL_REG, D.CUSUAR_RESP_ATULZ, D.CSGL_DEPTO_DEP, D.CIND_REG_ATIVO, D.CDEPTO_DEP_IDTFD FROM DBPROD.DEPTO_DEP_IDTFD D";

	
	public static final String DEPARTAMENTO_OBTERCOMRESTRICAODEPARAMETRODEPOSITO = CAMPOS_SELECT_DEPARTAMENTO + 
			"FROM DBPROD.DEPTO_DEP_IDTFD D, DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.PARMZ_DEP_IDTFD P " + 
			"WHERE D.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND P.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND P.CINTRN_CIA_SEGDR = G.CINTRN_CIA_SEGDR AND G.CIND_REG_ATIVO = 'S' AND D.CIND_REG_ATIVO = 'S' AND P.CIND_REG_ATIVO = 'S' AND A.CIND_REG_ATIVO = 'S' AND A.CGRP_DEPTO_DEP = G.CGRP_DEPTO_DEP AND G.CINTRN_CIA_SEGDR = :whr1 AND A.CUSUAR_DEP_IDTFD = :whr2 ORDER BY D.CDEPTO_DEP_IDTFD ASC"; 

	public static final String DEPARTAMENTO_OBTERCOMRESTRICAODECONTACORRENTEMOTIVODEPOSITO = CAMPOS_SELECT_DEPARTAMENTO +
			"FROM DBPROD.DEPTO_DEP_IDTFD D, DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.CTA_CORR_MOTVO_DEP MD " + 
			"WHERE 	G.CIND_REG_ATIVO = 'S' AND D.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND MD.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND MD.CINTRN_CIA_SEGDR = G.CINTRN_CIA_SEGDR and D.CIND_REG_ATIVO = 'S' " +
			"and MD.CIND_REG_ATIVO = 'S' AND A.CIND_REG_ATIVO = 'S' AND A.CGRP_DEPTO_DEP = G.CGRP_DEPTO_DEP AND G.CINTRN_CIA_SEGDR = :whr1 AND A.CUSUAR_DEP_IDTFD = :whr2 ORDER BY D.CDEPTO_DEP_IDTFD ASC";

	public static final String DEPARTAMENTO_OBTERCOMRESTRICAODEDEPOSITO = CAMPOS_SELECT_DEPARTAMENTO +
			"FROM DBPROD.DEPTO_DEP_IDTFD D, DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.DEP_IDTFD DEP " + 
			"WHERE G.CIND_REG_ATIVO = 'S' AND D.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND DEP.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND DEP.CINTRN_CIA_SEGDR = G.CINTRN_CIA_SEGDR and D.CIND_REG_ATIVO = 'S' " + 
			"and DEP.CIND_REG_ATIVO = 'S' AND A.CIND_REG_ATIVO = 'S' AND A.CGRP_DEPTO_DEP = G.CGRP_DEPTO_DEP AND G.CINTRN_CIA_SEGDR = :whr1 AND A.CUSUAR_DEP_IDTFD = :whr2 ORDER BY D.CDEPTO_DEP_IDTFD ASC";

	public static final String DEPARTAMENTO_INSERT = "INSERT INTO DBPROD.DEPTO_DEP_IDTFD (CSGL_DEPTO_DEP, IDEPTO_DEP_IDTFD, DHORA_INCL_REG, DHORA_ULT_ATULZ, CUSUAR_RESP_ATULZ, CIND_REG_ATIVO) " +
			"VALUES (:prm1, :prm2, CURRENT TIMESTAMP, CURRENT TIMESTAMP, :prm3, 'S')";

	public static final String DEPARTAMENTO_UPDATE = "UPDATE DBPROD.DEPTO_DEP_IDTFD SET CSGL_DEPTO_DEP = :prm1, IDEPTO_DEP_IDTFD = :prm2, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm3 " +
			"WHERE CDEPTO_DEP_IDTFD = :whr1 AND CIND_REG_ATIVO = 'S'";

	public static final String DEPARTAMENTO_INATIVAR = "UPDATE DBPROD.DEPTO_DEP_IDTFD SET DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CIND_REG_ATIVO = 'N', CUSUAR_RESP_ATULZ = :prm1 WHERE CDEPTO_DEP_IDTFD = :whr1 AND CIND_REG_ATIVO = 'S'";

	public static final String DEPARTAMENTO_OBTERPORCOMPANHIASEGURADORA = "SELECT DBPROD.DEPTO_DEP_IDTFD.IDEPTO_DEP_IDTFD, DBPROD.DEPTO_DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.DEPTO_DEP_IDTFD.DHORA_INCL_REG, DBPROD.DEPTO_DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEPTO_DEP_IDTFD.CSGL_DEPTO_DEP, DBPROD.DEPTO_DEP_IDTFD.CIND_REG_ATIVO, DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD " + 
			"FROM DBPROD.DEPTO_DEP_IDTFD, DBPROD.CIA_DEPTO_DEP, DBPROD.COD_INTRN_CIA " +
			"WHERE 	DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD AND DBPROD.CIA_DEPTO_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = :whr1"; 

	public static final String GRUPOACESSO_EXISTS= "SELECT CGRP_DEPTO_DEP, CIND_REG_ATIVO FROM DBPROD.GRP_DEPTO_DEP WHERE CDEPTO_DEP_IDTFD = :whr1 AND CINTRN_CIA_SEGDR = :whr2";

	public static final String GRUPOACESSO_EXISTSUSUARIOALOCADOATIVO = "SELECT CUSUAR_DEP_IDTFD FROM DBPROD.ALOC_USUAR_GRP_DEP WHERE CGRP_DEPTO_DEP = :whr1 AND CIND_REG_ATIVO = 'S'";

	public static final String GRUPOACESSO_REFERENCIADO_PARAMETRODEPOSITO = "SELECT 1 FROM DBPROD.PARMZ_DEP_IDTFD WHERE CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CIND_REG_ATIVO = 'S'";

	public static final String GRUPOACESSO_DESATIVAR = "UPDATE DBPROD.GRP_DEPTO_DEP SET CUSUAR_RESP_ATULZ = :prm1, CIND_REG_ATIVO = 'N', DHORA_ULT_ATULZ = CURRENT TIMESTAMP WHERE CGRP_DEPTO_DEP = :whr1";

	public static final String GRUPOACESSO_UPDATE = "UPDATE DBPROD.GRP_DEPTO_DEP SET CUSUAR_RESP_ATULZ = :prm1, DHORA_ULT_ATULZ = CURRENT TIMESTAMP WHERE CGRP_DEPTO_DEP = :whr1";

	public static final String GRUPOACESSO_ALOCARFUNCIONARIO = "INSERT INTO DBPROD.ALOC_USUAR_GRP_DEP (CGRP_DEPTO_DEP, CUSUAR_DEP_IDTFD, CUSUAR_RESP_ATULZ, DHORA_INCL_REG, DHORA_ULT_ATULZ, CIND_REG_ATIVO) VALUES (:prm1, :prm2, :prm3, CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'S')";

	public static final String GRUPOACESSO_DESALOCARFUNCIONARIO = "UPDATE DBPROD.ALOC_USUAR_GRP_DEP SET CUSUAR_RESP_ATULZ = :prm1, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CIND_REG_ATIVO = 'N' WHERE CGRP_DEPTO_DEP = :whr1 AND CUSUAR_DEP_IDTFD = :whr2"; 

	public static final String GRUPOACESSO_REALOCARFUNCIONARIO = "UPDATE DBPROD.ALOC_USUAR_GRP_DEP SET CUSUAR_RESP_ATULZ = :prm1, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CIND_REG_ATIVO = 'S' WHERE CGRP_DEPTO_DEP = :whr1 AND CUSUAR_DEP_IDTFD = :whr2"; 

	public static final String GRUPOACESSO_EXISTSATIVO = "SELECT CGRP_DEPTO_DEP FROM DBPROD.GRP_DEPTO_DEP WHERE CDEPTO_DEP_IDTFD = :whr1 AND CINTRN_CIA_SEGDR = :whr2 AND CIND_REG_ATIVO = 'S'";

	public static final String GRUPOACESSO_INSERT = "INSERT INTO DBPROD.GRP_DEPTO_DEP (CDEPTO_DEP_IDTFD, CINTRN_CIA_SEGDR, CUSUAR_RESP_ATULZ, DHORA_INCL_REG, DHORA_ULT_ATULZ, CIND_REG_ATIVO) VALUES (:prm1, :prm2, :prm3, CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'S')";

	public static final String GRUPOACESSO_OBTERPORFILTRO = "SELECT DISTINCT DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP, DBPROD.GRP_DEPTO_DEP.CINTRN_CIA_SEGDR, DBPROD.GRP_DEPTO_DEP.CDEPTO_DEP_IDTFD, " + 
			"DBPROD.GRP_DEPTO_DEP.DHORA_INCL_REG, DBPROD.GRP_DEPTO_DEP.DHORA_ULT_ATULZ, DBPROD.GRP_DEPTO_DEP.CIND_REG_ATIVO, DBPROD.GRP_DEPTO_DEP.CUSUAR_RESP_ATULZ " +
			"FROM DBPROD.DEPTO_DEP_IDTFD, DBPROD.CIA_DEPTO_DEP, DBPROD.GRP_DEPTO_DEP, DBPROD.ALOC_USUAR_GRP_DEP, DBPROD.USUAR_DEP_IDTFD, DBPROD.COD_INTRN_CIA " +
			"WHERE DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD = DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD AND DBPROD.GRP_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD " +
			"AND DBPROD.GRP_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR AND DBPROD.ALOC_USUAR_GRP_DEP.CGRP_DEPTO_DEP = DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP " +
			"AND DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR AND DBPROD.USUAR_DEP_IDTFD.CUSUAR_DEP_IDTFD = DBPROD.ALOC_USUAR_GRP_DEP.CUSUAR_DEP_IDTFD " +
			"AND DBPROD.ALOC_USUAR_GRP_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.GRP_DEPTO_DEP.CIND_REG_ATIVO = 'S' # ORDER BY DBPROD.GRP_DEPTO_DEP.DHORA_ULT_ATULZ DESC";

	public static final String GRUPOACESSO_OBTERPORFILTRONEW = "SELECT DISTINCT DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP, DBPROD.GRP_DEPTO_DEP.CINTRN_CIA_SEGDR, DBPROD.GRP_DEPTO_DEP.CDEPTO_DEP_IDTFD, " +
			"DBPROD.GRP_DEPTO_DEP.DHORA_INCL_REG, DBPROD.GRP_DEPTO_DEP.DHORA_ULT_ATULZ, DBPROD.GRP_DEPTO_DEP.CIND_REG_ATIVO, DBPROD.GRP_DEPTO_DEP.CUSUAR_RESP_ATULZ, DBPROD.DEPTO_DEP_IDTFD.CSGL_DEPTO_DEP, DBPROD.DEPTO_DEP_IDTFD.IDEPTO_DEP_IDTFD " + 
			"FROM DBPROD.DEPTO_DEP_IDTFD INNER JOIN DBPROD.CIA_SEGDR ON DBPROD.CIA_SEGDR.CCIA_SEGDR = DBPROD.COD_INTRN_CIA.CCIA_SEGDR AND DBPROD.CIA_SEGDR.CCIA_SEGDR = DBPROD.COD_INTRN_CIA.CCIA_SEGDR " + 
			"INNER JOIN DBPROD.COD_INTRN_CIA ON DBPROD.COD_INTRN_CIA.CINTRN_CIA_SEGDR = DBPROD.CIA_DEPTO_DEP.CINTRN_CIA_SEGDR " +
			"INNER JOIN DBPROD.CIA_DEPTO_DEP ON DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.DEPTO_DEP_IDTFD.CDEPTO_DEP_IDTFD " + 
			"INNER JOIN DBPROD.GRP_DEPTO_DEP ON DBPROD.GRP_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.CIA_DEPTO_DEP.CDEPTO_DEP_IDTFD AND DBPROD.GRP_DEPTO_DEP.CIND_REG_ATIVO = 'S' " +
			"INNER JOIN DBPROD.ALOC_USUAR_GRP_DEP ON DBPROD.ALOC_USUAR_GRP_DEP.CGRP_DEPTO_DEP = DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP AND DBPROD.ALOC_USUAR_GRP_DEP.CIND_REG_ATIVO = 'S'  "+ 
			"INNER JOIN DBPROD.USUAR_DEP_IDTFD ON DBPROD.USUAR_DEP_IDTFD.CUSUAR_DEP_IDTFD = DBPROD.ALOC_USUAR_GRP_DEP.CUSUAR_DEP_IDTFD WHERE 0=0  {0}  ORDER BY DBPROD.GRP_DEPTO_DEP.DHORA_ULT_ATULZ DESC";

	public static final String GRUPOACESSO_OBTERGRUPOPORCHAVE = "SELECT GRP.CDEPTO_DEP_IDTFD, GRP.CGRP_DEPTO_DEP, GRP.CIND_REG_ATIVO, GRP.CINTRN_CIA_SEGDR, GRP.CUSUAR_RESP_ATULZ, GRP.DHORA_INCL_REG, GRP.DHORA_ULT_ATULZ, DEPTO.CIND_REG_ATIVO, DEPTO.CSGL_DEPTO_DEP, DEPTO.IDEPTO_DEP_IDTFD, CIA.CCIA_SEGDR FROM DBPROD.GRP_DEPTO_DEP GRP, DBPROD.DEPTO_DEP_IDTFD DEPTO, DBPROD.COD_INTRN_CIA CIA " +
			"WHERE DEPTO.CDEPTO_DEP_IDTFD = GRP.CDEPTO_DEP_IDTFD AND CIA.CINTRN_CIA_SEGDR = GRP.CINTRN_CIA_SEGDR AND GRP.CGRP_DEPTO_DEP = :whr1 AND GRP.CDEPTO_DEP_IDTFD IN (SELECT DEP.CDEPTO_DEP_IDTFD FROM DBPROD.DEPTO_DEP_IDTFD DEP)"; 

	public static final String GRUPOACESSO_OBTERPORMOTIVODEPOSITO = "SELECT DISTINCT CA.CBCO, CA.CAG_BCRIA, CA.CCTA_CORR, CA.ROBS_CTA_AUTRZ, CA.DHORA_INCL_REG, CA.DHORA_ULT_ATULZ, CA.CCTA_CORR_AUTRZ, CA.CUSUAR_RESP_ATULZ, CA.CIND_REG_ATIVO, CA.CDIG_AG, CA.CPRIM_DIG_CTA, CA.CSEGDA_DIG_CTA, CA.CINTRN_CIA_SEGDR " + 
			"FROM DBPROD.PARMZ_DEP_IDTFD MD INNER JOIN DBPROD.CTA_CORR_MOTVO_DEP CM ON (MD.CMOTVO_DEP_IDTFD = CM.CMOTVO_DEP_IDTFD)  INNER JOIN DBPROD.CTA_CORR_AUTRZ CA ON (CA.CCTA_CORR_AUTRZ = CM.CCTA_CORR_AUTRZ)  " + 
			"WHERE MD.CIND_REG_ATIVO = 'S' AND CM.CIND_REG_ATIVO = 'N' AND CA.CIND_REG_ATIVO = 'N'  AND MD.CMOTVO_DEP_IDTFD = :whr1"; 

	public static final String ALOCACAO_EXISTSUSUARIO = "SELECT CIND_REG_ATIVO FROM DBPROD.ALOC_USUAR_GRP_DEP WHERE CGRP_DEPTO_DEP = :whr1 AND CUSUAR_DEP_IDTFD = :whr2";

	public static final String CIA_OBTERCOMRESTRICAODEGRUPOACESSO = "SELECT DISTINCT G.CINTRN_CIA_SEGDR FROM DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A " +
			"WHERE A.CGRP_DEPTO_DEP = G.CGRP_DEPTO_DEP AND A.CUSUAR_DEP_IDTFD = :whr1 AND A.CIND_REG_ATIVO = 'S' ORDER BY G.CINTRN_CIA_SEGDR ASC";

	public static final String CIA_OBTERCOMRESTRICAODEPARAMETRODEPOSITO = "SELECT DISTINCT G.CINTRN_CIA_SEGDR FROM 	DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.PARMZ_DEP_IDTFD P, DBPROD.CTA_CORR_AUTRZ C " + 
			"WHERE A.CGRP_DEPTO_DEP = G.CGRP_DEPTO_DEP AND G.CIND_REG_ATIVO = 'S' AND P.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND P.CINTRN_CIA_SEGDR = G.CINTRN_CIA_SEGDR AND C.CINTRN_CIA_SEGDR  = G.CINTRN_CIA_SEGDR AND P.CIND_REG_ATIVO = A.CIND_REG_ATIVO " + 
			"AND A.CUSUAR_DEP_IDTFD = :whr1 AND A.CIND_REG_ATIVO = 'S' ORDER BY G.CINTRN_CIA_SEGDR ASC"; 

	public static final String CIA_OBTERCOMRESTRICAODECONTACORRENTEMOTIVODEPOSITO= "SELECT DISTINCT M.CINTRN_CIA_SEGDR FROM DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.CTA_CORR_MOTVO_DEP M " +
			"WHERE A.CGRP_DEPTO_DEP = G.CGRP_DEPTO_DEP AND M.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD AND M.CINTRN_CIA_SEGDR = G.CINTRN_CIA_SEGDR AND A.CUSUAR_DEP_IDTFD = :whr1 AND M.CIND_REG_ATIVO = 'S' AND G.CIND_REG_ATIVO = 'S' AND A.CIND_REG_ATIVO = 'S' ORDER BY M.CINTRN_CIA_SEGDR ASC";

	public static final String CIA_OBTERCOMRESTRICAODEDEPOSITO = "SELECT DISTINCT D.CINTRN_CIA_SEGDR FROM DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.DEP_IDTFD D " + 
			"WHERE 	A.CGRP_DEPTO_DEP = G.CGRP_DEPTO_DEP AND D.CDEPTO_DEP_IDTFD = G.CDEPTO_DEP_IDTFD  AND D.CINTRN_CIA_SEGDR = G.CINTRN_CIA_SEGDR AND A.CUSUAR_DEP_IDTFD = :whr1 AND D.CIND_REG_ATIVO = 'S' AND G.CIND_REG_ATIVO = 'S' AND A.CIND_REG_ATIVO = 'S' ORDER BY D.CINTRN_CIA_SEGDR ASC";

	public static final String MOTIVODEPOSITO_EXISTS = "SELECT CMOTVO_DEP_IDTFD, RMOTVO_DEP_IDTFD, RDETLH_MOTVO_DEP, CTPO_EVNTO_NEGOC,CTPO_ITEM_NEGOC, DHORA_INCL_REG, DHORA_ULT_ATULZ,CUSUAR_RESP_ATULZ,CIND_REG_ATIVO FROM DBPROD.MOTVO_DEP_IDTFD WHERE RMOTVO_DEP_IDTFD = :whr1";

	public static final String MOTIVODEPOSITO_INSERT = "INSERT INTO DBPROD.MOTVO_DEP_IDTFD (RMOTVO_DEP_IDTFD, RDETLH_MOTVO_DEP, CTPO_EVNTO_NEGOC,CTPO_ITEM_NEGOC, DHORA_INCL_REG, DHORA_ULT_ATULZ,CUSUAR_RESP_ATULZ,CIND_REG_ATIVO) " +  
			"VALUES (:prm1,:prm2,:prm3,:prm4,CURRENT TIMESTAMP, CURRENT TIMESTAMP,:prm5,'S')";  

	public static final String MOTIVODEPOSITO_OBTERPORCHAVE = "SELECT CMOTVO_DEP_IDTFD, RMOTVO_DEP_IDTFD, RDETLH_MOTVO_DEP, CTPO_EVNTO_NEGOC,CTPO_ITEM_NEGOC, DHORA_INCL_REG, DHORA_ULT_ATULZ,CUSUAR_RESP_ATULZ,CIND_REG_ATIVO " + 
			"FROM DBPROD.MOTVO_DEP_IDTFD WHERE CMOTVO_DEP_IDTFD = :whr1";  
	
	public static final String MOTIVODEPOSITO_ALL = "SELECT CMOTVO_DEP_IDTFD, RMOTVO_DEP_IDTFD, RDETLH_MOTVO_DEP, CTPO_EVNTO_NEGOC,CTPO_ITEM_NEGOC, DHORA_INCL_REG, DHORA_ULT_ATULZ,CUSUAR_RESP_ATULZ,CIND_REG_ATIVO  " + 
			"FROM DBPROD.MOTVO_DEP_IDTFD";  
	
	public static final String MOTIVODEPOSITO_REFERENCIADO_PARAMETRODEPOSITO = "SELECT 1 FROM DBPROD.PARMZ_DEP_IDTFD  " + 
			"WHERE CIND_REG_ATIVO = 'S' AND CMOTVO_DEP_IDTFD = :whr1";

	public static final String MOTIVODEPOSITO_UPDATE = "UPDATE DBPROD.MOTVO_DEP_IDTFD SET RMOTVO_DEP_IDTFD = :prm1, RDETLH_MOTVO_DEP = :prm2, CTPO_EVNTO_NEGOC = :prm3, CTPO_ITEM_NEGOC = :prm4, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm5 " + 
			"WHERE CMOTVO_DEP_IDTFD = :whr1";

	public static final String MOTIVODEPOSITO_INATIVAR= "UPDATE DBPROD.MOTVO_DEP_IDTFD SET CIND_REG_ATIVO = 'N', DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm1  " + 
			"WHERE CMOTVO_DEP_IDTFD = :whr1";

	public static final String MOTIVODEPOSITO_ATIVAR = "UPDATE DBPROD.MOTVO_DEP_IDTFD SET CIND_REG_ATIVO = 'S', DHORA_ULT_ATULZ = CURRENT TIMESTAMP, RDETLH_MOTVO_DEP = :prm1, CTPO_EVNTO_NEGOC = :prm2, CTPO_ITEM_NEGOC = :prm3, CUSUAR_RESP_ATULZ = :prm4  " + 
			"WHERE CMOTVO_DEP_IDTFD = :whr1";

	public static final String MOTIVODEPOSITO_OBTERCOMRESTRICAODEPARAMETRODEPOSITO = "SELECT DISTINCT M_CMOTVO_DEP_IDTFD, M_RMOTVO_DEP_IDTFD, M_RDETLH_MOTVO_DEP, M_DHORA_INCL_REG, M_CUSUAR_RESP_ATULZ, M_DHORA_ULT_ATULZ, M_CIND_REG_ATIVO, M_CTPO_EVNTO_NEGOC, M_CTPO_ITEM_NEGOC FROM 	DBPROD.MOTVO_DEP_IDTFD M, DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.PARMZ_DEP_IDTFD P " + 
			"WHERE 	M_CMOTVO_DEP_IDTFD = P_CMOTVO_DEP_IDTFD AND M_CIND_REG_ATIVO = 'S' AND P_CINTRN_CIA_SEGDR = G_CINTRN_CIA_SEGDR AND P_CDEPTO_DEP_IDTFD = G_CDEPTO_DEP_IDTFD AND P_CINTRN_CIA_SEGDR = :whr1 AND P_CDEPTO_DEP_IDTFD = whr2 AND P_CIND_REG_ATIVO = 'S' AND G_CIND_REG_ATIVO = 'S' AND A_CGRP_DEPTO_DEP = G_CGRP_DEPTO_DEP AND A_CUSUAR_DEP_IDTFD = :whr3 AND A_CIND_REG_ATIVO = 'S' ORDER BY M_CMOTVO_DEP_IDTFD ASC"; 

	public static final String MOTIVODEPOSITO_OBTERCOMRESTRICAODECONTACORRENTEMOTIVODEPOSITO = "SELECT DISTINCT M_CMOTVO_DEP_IDTFD, M_RMOTVO_DEP_IDTFD, M_RDETLH_MOTVO_DEP, M_DHORA_INCL_REG, M_CUSUAR_RESP_ATULZ, M_DHORA_ULT_ATULZ, M_CIND_REG_ATIVO, M_CTPO_EVNTO_NEGOC, M_CTPO_ITEM_NEGOC FROM 	DBPROD.MOTVO_DEP_IDTFD M, DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.CTA_CORR_MOTVO_DEP CM " + 
			"WHERE 	M_CMOTVO_DEP_IDTFD = CM_CMOTVO_DEP_IDTFD AND G_CINTRN_CIA_SEGDR = CM_CINTRN_CIA_SEGDR AND G_CDEPTO_DEP_IDTFD = CM_CDEPTO_DEP_IDTFD AND A_CGRP_DEPTO_DEP = G_CGRP_DEPTO_DEP AND CM_CINTRN_CIA_SEGDR = :whr1 AND CM_CDEPTO_DEP_IDTFD = :whr2 AND A_CUSUAR_DEP_IDTFD = :whr3 AND M_CIND_REG_ATIVO = 'S' AND CM_CIND_REG_ATIVO = 'S' AND G_CIND_REG_ATIVO = 'S' AND A_CIND_REG_ATIVO = 'S' ORDER BY M_CMOTVO_DEP_IDTFD ASC";

	public static final String MOTIVODEPOSITO_OBTERCOMRESTRICAODEDEPOSITO = "SELECT DISTINCT M_CMOTVO_DEP_IDTFD, M_RMOTVO_DEP_IDTFD, M_RDETLH_MOTVO_DEP, M_DHORA_INCL_REG, M_CUSUAR_RESP_ATULZ, M_DHORA_ULT_ATULZ, M_CIND_REG_ATIVO, M_CTPO_EVNTO_NEGOC, M_CTPO_ITEM_NEGOC FROM 	DBPROD.MOTVO_DEP_IDTFD M, DBPROD.GRP_DEPTO_DEP G, DBPROD.ALOC_USUAR_GRP_DEP A, DBPROD.DEP_IDTFD DEP " + 
			"WHERE M_CMOTVO_DEP_IDTFD = DEP_CMOTVO_DEP_IDTFD AND G_CINTRN_CIA_SEGDR = DEP_CINTRN_CIA_SEGDR AND G_CDEPTO_DEP_IDTFD = DEP_CDEPTO_DEP_IDTFD AND A_CGRP_DEPTO_DEP = G_CGRP_DEPTO_DEP AND DEP_CINTRN_CIA_SEGDR = :whr1 AND DEP_CDEPTO_DEP_IDTFD = :whr2 AND A_CUSUAR_DEP_IDTFD = :whr3 AND M_CIND_REG_ATIVO = 'S' AND DEP_CIND_REG_ATIVO = 'S' AND G_CIND_REG_ATIVO = 'S' AND A_CIND_REG_ATIVO = 'S' ORDER BY M_CMOTVO_DEP_IDTFD ASC";

	public static final String PARAMETRODEPOSITO_EXISTS = "SELECT CIND_REG_ATIVO FROM DBPROD.PARMZ_DEP_IDTFD WHERE CINTRN_CIA_SEGDR = :prm1 AND  CDEPTO_DEP_IDTFD = ;prm2 AND CMOTVO_DEP_IDTFD = :prm3"; 
	
	public static final String PARAMETRODEPOSITO_OBTERPORCHAVE = "SELECT DBPROD.PARMZ_DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.PARMZ_DEP_IDTFD.CDEPTO_DEP_IDTFD, DBPROD.PARMZ_DEP_IDTFD.CMOTVO_DEP_IDTFD, DBPROD.PARMZ_DEP_IDTFD.CIND_DEP_APOS_VCTO, DBPROD.PARMZ_DEP_IDTFD.QDIA_APOS_VCTO, DBPROD.PARMZ_DEP_IDTFD.CIND_ITEM_APOLC, DBPROD.PARMZ_DEP_IDTFD.CIND_RAMO_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_TPO_DOCTO, DBPROD.PARMZ_DEP_IDTFD.CIND_SUCUR_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_PROT, DBPROD.PARMZ_DEP_IDTFD.CIND_APOLC_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_CPF_CNPJ, DBPROD.PARMZ_DEP_IDTFD.CIND_PROCS_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_BLETO_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_ENDSS_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_PCELA_PRMIO, DBPROD.PARMZ_DEP_IDTFD.ROBS_PARMZ_DEP, DBPROD.PARMZ_DEP_IDTFD.DHORA_INCL_REG, DBPROD.PARMZ_DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.PARMZ_DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.PARMZ_DEP_IDTFD.CIND_REG_ATIVO " + 
	         "FROM DBPROD.PARMZ_DEP_IDTFD WHERE CINTRN_CIA_SEGDR = :prm1 AND  CDEPTO_DEP_IDTFD = ;prm2 AND CMOTVO_DEP_IDTFD = :prm3"; 

	public static final String PARAMETRODEPOSITO_INSERT = "INSERT INTO DBPROD.PARMZ_DEP_IDTFD (CINTRN_CIA_SEGDR,CDEPTO_DEP_IDTFD,CMOTVO_DEP_IDTFD,CIND_DEP_APOS_VCTO,QDIA_APOS_VCTO, CIND_SUCUR_OBRIG, CIND_APOLC_OBRIG, CIND_ENDSS_OBRIG, CIND_ITEM_APOLC, CIND_BLETO_OBRIG, CIND_CPF_CNPJ, CIND_PROCS_OBRIG, CIND_PROT, CIND_TPO_DOCTO, CIND_RAMO_OBRIG, CIND_PCELA_PRMIO, ROBS_PARMZ_DEP,CUSUAR_RESP_ATULZ, DHORA_INCL_REG,DHORA_ULT_ATULZ,CIND_REG_ATIVO)" + 
			"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT TIMESTAMP,CURRENT TIMESTAMP,'S')";

	public static final String PARAMETRODEPOSITO_UPDATEREFERENCIADO = "UPDATE DBPROD.PARMZ_DEP_IDTFD SET ROBS_PARMZ_DEP = :prm1, CUSUAR_RESP_ATULZ = :prm2, DHORA_ULT_ATULZ = CURRENT TIMESTAMP " + 
		    "WHERE CIND_REG_ATIVO = 'S' AND CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2  AND CMOTVO_DEP_IDTFD = :whr3";

	public static final String PARAMETRODEPOSITO_UPDATENAOREFERENCIADO = "UPDATE DBPROD.PARMZ_DEP_IDTFD SET CIND_DEP_APOS_VCTO = :prm1 , QDIA_APOS_VCTO = :prm2,  CIND_SUCUR_OBRIG = :prm3, CIND_APOLC_OBRIG = :prm4, CIND_ENDSS_OBRIG = :prm5, CIND_ITEM_APOLC = :prm6, CIND_BLETO_OBRIG = :prm7,  CIND_CPF_CNPJ = :prm8, CIND_PROCS_OBRIG = :prm9, CIND_PROT = :prm10, CIND_TPO_DOCTO = :prm11, CIND_RAMO_OBRIG = :prm12,  CIND_PCELA_PRMIO = :prm13, ROBS_PARMZ_DEP = :prm14, CUSUAR_RESP_ATULZ = :prm15, DHORA_ULT_ATULZ = CURRENT TIMESTAMP " + 
			"WHERE CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = :whr3";
	
	public static final String PARAMETRODEPOSITO_REATIVAR = "UPDATE DBPROD.PARMZ_DEP_IDTFD SET CIND_DEP_APOS_VCTO = :prm1 , QDIA_APOS_VCTO = :prm2,  CIND_SUCUR_OBRIG = :prm3, CIND_APOLC_OBRIG = :prm4, " + 
			"CIND_ENDSS_OBRIG = :prm5, CIND_ITEM_APOLC = :prm6, CIND_BLETO_OBRIG = :prm7, CIND_CPF_CNPJ = :prm8, CIND_PROCS_OBRIG = :prm9, CIND_PROT = :prm10, CIND_TPO_DOCTO = :prm11,  CIND_RAMO_OBRIG = :prm12, " +
			"CIND_PCELA_PRMIO = :prm13, ROBS_PARMZ_DEP = :prm14, CUSUAR_RESP_ATULZ = :prm15, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CIND_REG_ATIVO = 'S' " + 
			"WHERE CIND_REG_ATIVO = 'N' AND CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = whr3"; 
	
	public static final String PARAMETRODEPOSITO_INATIVAR = "UPDATE DBPROD.PARMZ_DEP_IDTFD SET CUSUAR_RESP_ATULZ = :prm1 , DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CIND_REG_ATIVO = 'N' " + 
			"WHERE CIND_REG_ATIVO = 'S' AND CINTRN_CIA_SEGDR = :whr1 AND CDEPTO_DEP_IDTFD = :whr2 AND CMOTVO_DEP_IDTFD = :whr3"; 

	public static final String PARAMETRODEPOSITO_ASSOCIACAOMOTIVODEPOSITO_REFERENCIADO = "SELECT 1 FROM DBPROD.CTA_CORR_MOTVO_DEP WHERE CIND_REG_ATIVO = 'S' AND CINTRN_CIA_SEGDR = :prm1 AND CDEPTO_DEP_IDTFD = :prm2 AND CMOTVO_DEP_IDTFD = :prm3";

	public static final String PARAMETRODEPOSITO_DEPOSITO_REFERENCIADO = "SELECT 1 FROM DBPROD.DEP_IDTFD WHERE CIND_REG_ATIVO = 'S' AND CINTRN_CIA_SEGDR = :prm1 AND CDEPTO_DEP_IDTFD = :prm2 AND CMOTVO_DEP_IDTFD = :prm3";

	public static final String PARAMETRODEPOSITO_OBTERPORFILTRO = "SELECT DBPROD.PARMZ_DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.PARMZ_DEP_IDTFD.CDEPTO_DEP_IDTFD, DBPROD.PARMZ_DEP_IDTFD.CMOTVO_DEP_IDTFD, DBPROD.PARMZ_DEP_IDTFD.CIND_DEP_APOS_VCTO, DBPROD.PARMZ_DEP_IDTFD.QDIA_APOS_VCTO, DBPROD.PARMZ_DEP_IDTFD.CIND_ITEM_APOLC, DBPROD.PARMZ_DEP_IDTFD.CIND_RAMO_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_TPO_DOCTO, DBPROD.PARMZ_DEP_IDTFD.CIND_SUCUR_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_PROT, DBPROD.PARMZ_DEP_IDTFD.CIND_APOLC_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_CPF_CNPJ, DBPROD.PARMZ_DEP_IDTFD.CIND_PROCS_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_BLETO_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_ENDSS_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_PCELA_PRMIO, DBPROD.PARMZ_DEP_IDTFD.ROBS_PARMZ_DEP, DBPROD.PARMZ_DEP_IDTFD.DHORA_INCL_REG, DBPROD.PARMZ_DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.PARMZ_DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.PARMZ_DEP_IDTFD.CIND_REG_ATIVO " + 
			"FROM DBPROD.PARMZ_DEP_IDTFD, DBPROD.MOTVO_DEP_IDTFD, DBPROD.DEPTO_DEP_IDTFD " + 
			"WHERE DBPROD.PARMZ_DEP_IDTFD.CDEPTO_DEP_IDTFD = DBPROD.DEPTO_DEP_IDTFD_CDEPTO_DEP_IDTFD AND DBPROD.PARMZ_DEP_IDTFD.CMOTVO_DEP_IDTFD = DBPROD.MOTVO_DEP_IDTFD.CMOTVO_DEP_IDTFD AND DBPROD.PARMZ_DEP_IDTFD.CIND_REG_ATIVO = 'S' # ORDER BY DBPROD.PARMZ_DEP_IDTFD.DHORA_ULT_ATULZ DESC"; 

	public static final String PARAMETRODEPOSITO_OBTERPORFILTROCOMRESTRICAODEGRUPOACESSO = "SELECT DBPROD.PARMZ_DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.PARMZ_DEP_IDTFD.CDEPTO_DEP_IDTFD, DBPROD.PARMZ_DEP_IDTFD.CMOTVO_DEP_IDTFD, DBPROD.PARMZ_DEP_IDTFD.CIND_DEP_APOS_VCTO, DBPROD.PARMZ_DEP_IDTFD.QDIA_APOS_VCTO, DBPROD.PARMZ_DEP_IDTFD.CIND_ITEM_APOLC, DBPROD.PARMZ_DEP_IDTFD.CIND_RAMO_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_TPO_DOCTO, DBPROD.PARMZ_DEP_IDTFD.CIND_SUCUR_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_PROT, DBPROD.PARMZ_DEP_IDTFD.CIND_APOLC_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_CPF_CNPJ, DBPROD.PARMZ_DEP_IDTFD.CIND_PROCS_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_BLETO_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_ENDSS_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_PCELA_PRMIO, DBPROD.PARMZ_DEP_IDTFD.ROBS_PARMZ_DEP, DBPROD.PARMZ_DEP_IDTFD.DHORA_INCL_REG, DBPROD.PARMZ_DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.PARMZ_DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.PARMZ_DEP_IDTFD.CIND_REG_ATIVO " + 
			"FROM DBPROD.PARMZ_DEP_IDTFD, DBPROD.GRP_DEPTO_DEP, DBPROD.ALOC_USUAR_GRP_DEP, DBPROD.MOTVO_DEP_IDTFD, DBPROD.DEPTO_DEP_IDTFD " + 
			"WHERE  DBPROD.GRP_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.PARMZ_DEP_IDTFD.CDEPTO_DEP_IDTFD AND DBPROD.GRP_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.PARMZ_DEP_IDTFD.CINTRN_CIA_SEGDR AND 	DBPROD.GRP_DEPTO_DEP.CIND_REG_ATIVO = 'S' AND 	DBPROD.ALOC_USUAR_GRP_DEP.CGRP_DEPTO_DEP = DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP AND 	DBPROD.ALOC_USUAR_GRP_DEP.CIND_REG_ATIVO = 'S' AND   DBPROD.PARMZ_DEP_IDTFD.CMOTVO_DEP_IDTFD = DBPROD.MOTVO_DEP_IDTFD.CMOTVO_DEP_IDTFD AND   DBPROD.PARMZ_DEP_IDTFD.CIND_REG_ATIVO = 'S' AND 	DBPROD.DEPTO_DEP_IDTFD_CDEPTO_DEP_IDTFD = DBPROD.PARMZ_DEP_IDTFD.CDEPTO_DEP_IDTFD AND DBPROD.DEPTO_DEP_IDTFD_CIND_REG_ATIVO = 'S' # " + 
			"ORDER BY DBPROD.PARMZ_DEP_IDTFD.DHORA_ULT_ATULZ DESC";
	
	public static final String PARAMETRODEPOSITO_OBTERPORMOTIVO = "SELECT DBPROD.PARMZ_DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.PARMZ_DEP_IDTFD.CDEPTO_DEP_IDTFD, DBPROD.PARMZ_DEP_IDTFD.CMOTVO_DEP_IDTFD, DBPROD.PARMZ_DEP_IDTFD.CIND_DEP_APOS_VCTO, DBPROD.PARMZ_DEP_IDTFD.QDIA_APOS_VCTO, DBPROD.PARMZ_DEP_IDTFD.CIND_ITEM_APOLC, DBPROD.PARMZ_DEP_IDTFD.CIND_RAMO_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_TPO_DOCTO, DBPROD.PARMZ_DEP_IDTFD.CIND_SUCUR_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_PROT, DBPROD.PARMZ_DEP_IDTFD.CIND_APOLC_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_CPF_CNPJ, DBPROD.PARMZ_DEP_IDTFD.CIND_PROCS_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_BLETO_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_ENDSS_OBRIG, DBPROD.PARMZ_DEP_IDTFD.CIND_PCELA_PRMIO, DBPROD.PARMZ_DEP_IDTFD.ROBS_PARMZ_DEP, DBPROD.PARMZ_DEP_IDTFD.DHORA_INCL_REG, DBPROD.PARMZ_DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.PARMZ_DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.PARMZ_DEP_IDTFD.CIND_REG_ATIVO FROM DBPROD.PARMZ_DEP_IDTFD, DBPROD.MOTVO_DEP_IDTFD WHERE DBPROD.PARMZ_DEP_IDTFD.CDEPTO_DEP_IDTFD = DBPROD.CIA_DEPTO_DEP_CDEPTO_DEP_IDTFD AND DBPROD.PARMZ_DEP_IDTFD.CMOTVO_DEP_IDTFD = DBPROD.MOTVO_DEP_IDTFD.CMOTVO_DEP_IDTFD  AND DBPROD.PARMZ_DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.PARMZ_DEP_IDTFD.CMOTVO_DEP_IDTFD = ?  ORDER BY DBPROD.PARMZ_DEP_IDTFD.DHORA_ULT_ATULZ DESC";

	public static final String USUARIOS_OBTERPORFILTRO = "SELECT DBPROD.USUAR_DEP_IDTFD.CUSUAR_DEP_IDTFD, DBPROD.USUAR_DEP_IDTFD.IUSUAR_DEP_IDTFD, DBPROD.USUAR_DEP_IDTFD.DHORA_INCL_REG, DBPROD.USUAR_DEP_IDTFD.CIND_REG_ATIVO, DBPROD.USUAR_DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.USUAR_DEP_IDTFD.CUSUAR_RESP_ATULZ " + 
			"FROM DBPROD.USUAR_DEP_IDTFD WHERE DBPROD.USUAR_DEP_IDTFD.CIND_REG_ATIVO = 'S'";

	public static final String USUARIOS_OBTERPORGRUPOACESSO = "SELECT DBPROD.USUAR_DEP_IDTFD.CUSUAR_DEP_IDTFD, DBPROD.USUAR_DEP_IDTFD.IUSUAR_DEP_IDTFD, DBPROD.USUAR_DEP_IDTFD.DHORA_INCL_REG, DBPROD.USUAR_DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.USUAR_DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.USUAR_DEP_IDTFD.CIND_REG_ATIVO FROM DBPROD.ALOC_USUAR_GRP_DEP, DBPROD.USUAR_DEP_IDTFD  " + 
			"WHERE DBPROD.USUAR_DEP_IDTFD.CUSUAR_DEP_IDTFD = DBPROD.ALOC_USUAR_GRP_DEP.CUSUAR_DEP_IDTFD AND DBPROD.ALOC_USUAR_GRP_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.USUAR_DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.ALOC_USUAR_GRP_DEP.CGRP_DEPTO_DEP = :usrgrp ORDER BY DBPROD.ALOC_USUAR_GRP_DEP.DHORA_ULT_ATULZ DESC";

	public static final String DEPOSITO_OBTERPORFILTROCOMRESTRICAODEGRUPOACESSO = "SELECT DBPROD.DEP_IDTFD.CDEP_IDTFD, DBPROD.DEP_IDTFD.CDIG_DEP_IDTFD, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CDEPTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CMOTVO_DEP_IDTFD, DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, COALESCE(LPAD(CAST(DBPROD.DEP_IDTFD.CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,DBPROD.DEP_IDTFD.CRAMO_SEGUR_SAP) as CRAMO_SEGUR, DBPROD.DEP_IDTFD.CSUCUR_EMISR, DBPROD.DEP_IDTFD.NITEM_APOLC, DBPROD.DEP_IDTFD.NPROT, DBPROD.DEP_IDTFD.CTPO_DOCTO, DBPROD.DEP_IDTFD.NAPOLC, DBPROD.DEP_IDTFD.CPSSOA_DEPST, DBPROD.DEP_IDTFD.CPROCS_JURID, DBPROD.DEP_IDTFD.NBLETO_COBR, DBPROD.DEP_IDTFD.NENDSS, DBPROD.DEP_IDTFD.NPCELA_PRMIO, DBPROD.DEP_IDTFD.CTPO_GRP_RECEB, DBPROD.DEP_IDTFD.ROBS_DEP_IDTFD, DBPROD.DEP_IDTFD.CIND_DEP_PRROG, DBPROD.DEP_IDTFD.DVCTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CIND_DEP_CANCD, DBPROD.DEP_IDTFD.DPRROG_DEP_IDTFD, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.DEP_IDTFD.DCANCT_DEP_IDTFD, DBPROD.DEP_IDTFD.DHORA_INCL_REG, DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEP_IDTFD.CIND_REG_ATIVO, DBPROD.DEP_IDTFD.CSIT_DEP_IDTFD, DBPROD.DEPTO_DEP_IDTFD_CSGL_DEPTO_DEP, DBPROD.MOTVO_DEP_IDTFD.RMOTVO_DEP_IDTFD" + 
			"FROM  DBPROD.DEP_IDTFD, DBPROD.GRP_DEPTO_DEP, DBPROD.ALOC_USUAR_GRP_DEP, DBPROD.MOTVO_DEP_IDTFD,  DBPROD.DEPTO_DEP_IDTFD, DBPROD.CTA_CORR_AUTRZ" + 
			"WHERE DBPROD.GRP_DEPTO_DEP.CDEPTO_DEP_IDTFD = DBPROD.DEP_IDTFD.CDEPTO_DEP_IDTFD AND DBPROD.GRP_DEPTO_DEP.CINTRN_CIA_SEGDR = DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR AND DBPROD.ALOC_USUAR_GRP_DEP.CGRP_DEPTO_DEP = DBPROD.GRP_DEPTO_DEP.CGRP_DEPTO_DEP AND DBPROD.DEP_IDTFD.CMOTVO_DEP_IDTFD = DBPROD.MOTVO_DEP_IDTFD.CMOTVO_DEP_IDTFD AND DBPROD.DEPTO_DEP_IDTFD_CDEPTO_DEP_IDTFD = DBPROD.DEP_IDTFD.CDEPTO_DEP_IDTFD AND DBPROD.GRP_DEPTO_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.ALOC_USUAR_GRP_DEP.CIND_REG_ATIVO = 'S' AND DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.MOTVO_DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.DEPTO_DEP_IDTFD_CIND_REG_ATIVO = 'S' AND DBPROD.ALOC_USUAR_GRP_DEP.CUSUAR_DEP_IDTFD = ? AND DBPROD.DEP_IDTFD.CBCO = DBPROD.CTA_CORR_AUTRZ_CBCO AND DBPROD.DEP_IDTFD.CAG_BCRIA = DBPROD.CTA_CORR_AUTRZ_CAG_BCRIA AND DBPROD.DEP_IDTFD.CCTA_CORR = DBPROD.CTA_CORR_AUTRZ_CCTA_CORR # ORDER BY DBPROD.DEP_IDTFD.DHORA_ULT_ATULZ DESC"; 

	public static final String DEPOSITO_OBTERPORCHAVE = "SELECT DEP_CDEP_IDTFD, DEP_CDIG_DEP_IDTFD, DEP_CINTRN_CIA_SEGDR, DEP_CDEPTO_DEP_IDTFD, DEP_CMOTVO_DEP_IDTFD, DEP_CBCO, DEP_CAG_BCRIA, DEP_CCTA_CORR, COALESCE(LPAD(CAST(DEP_CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,DEP_CRAMO_SEGUR_SAP) as CRAMO_SEGUR, DEP_CSUCUR_EMISR, DEP_NITEM_APOLC, DEP_NPROT, DEP_CTPO_DOCTO, DEP_NAPOLC, DEP_CPSSOA_DEPST, DEP_CPROCS_JURID, DEP_NBLETO_COBR, DEP_NENDSS, DEP_NPCELA_PRMIO, DEP_CTPO_GRP_RECEB, DEP_ROBS_DEP_IDTFD, DEP_CIND_DEP_PRROG, DEP_DVCTO_DEP_IDTFD, DEP_CIND_DEP_CANCD, DEP_DPRROG_DEP_IDTFD, DEP_VDEP_IDTFD_ORIGN, DEP_DCANCT_DEP_IDTFD,  DEP_DHORA_INCL_REG, DEP_CSIT_DEP_ARQ_TRNSF, DEP_DHORA_ULT_ATULZ, DEP_CUSUAR_RESP_ATULZ, DEP_CIND_REG_ATIVO, DEP_CSIT_DEP_IDTFD, DEPTO_CSGL_DEPTO_DEP, DEPTO_IDEPTO_DEP_IDTFD, MOTVO_RMOTVO_DEP_IDTFD, MOTVO_RDETLH_MOTVO_DEP FROM DBPROD.DEP_IDTFD DEP, DBPROD.CTA_CORR_AUTRZ CTA, DBPROD.DEPTO_DEP_IDTFD DEPTO, DBPROD.MOTVO_DEP_IDTFD MOTVO WHERE DEP_CIND_REG_ATIVO = 'S' AND DEP_CDEP_IDTFD = ? AND MOTVO_CMOTVO_DEP_IDTFD = DEP_CMOTVO_DEP_IDTFD AND DEP_CBCO = DBPROD.CTA_CORR_AUTRZ_CBCO AND DEPTO_CDEPTO_DEP_IDTFD = DEP_CDEPTO_DEP_IDTFD AND DEP_CAG_BCRIA = DBPROD.CTA_CORR_AUTRZ_CAG_BCRIA AND DEP_CCTA_CORR = DBPROD.CTA_CORR_AUTRZ_CCTA_CORR";

	public static final String DEPOSITO_INSERT = "INSERT INTO DBPROD.DEP_IDTFD (CDIG_DEP_IDTFD, CINTRN_CIA_SEGDR,CDEPTO_DEP_IDTFD,CMOTVO_DEP_IDTFD,CBCO,CAG_BCRIA,CRAMO_SEGUR_SAP,CCTA_CORR, CSUCUR_EMISR,NITEM_APOLC,NPROT,CTPO_DOCTO,NAPOLC,CPSSOA_DEPST,CPROCS_JURID,NBLETO_COBR,NENDSS,NPCELA_PRMIO,CTPO_GRP_RECEB, CIND_DEP_PRROG,DVCTO_DEP_IDTFD,CIND_DEP_CANCD,DPRROG_DEP_IDTFD,VDEP_IDTFD_ORIGN,DCANCT_DEP_IDTFD, DHORA_INCL_REG,CSIT_DEP_ARQ_TRNSF,DHORA_ULT_ATULZ,CUSUAR_RESP_ATULZ,CIND_REG_ATIVO, ROBS_DEP_IDTFD, CSIT_DEP_IDTFD, CRAMO_SEGUR) " + 
			"VALUES (:prm1,:prm2,:prm3,:prm4,:prm5,:prm6,:prm7,:prm8,:prm9,:prm10,:prm11,:prm12,:prm13,:prm14,:prm15,:prm16,:prm17,:prm18, :prm19,'N',:prm20,'N',NULL,:prm21,NULL, CURRENT TIMESTAMP,1,CURRENT TIMESTAMP,:prm22,'S',:prm23, :prm24, NULL)";

	public static final String DEPOSITO_MOVIMENTO_INSERT = "INSERT INTO DBPROD.MOVTO_FINCR_DEP (CDEP_IDTFD,CTPO_ACAO_MOVTO,CCHEQ_DEVLC,CBCO,CAG_MOVTO,ROBS_MOVTO_FINCR,CCTA_MOVTO,DHORA_ULT_ATULZ,CUSUAR_RESP_ATULZ, CIND_REG_ATIVO) " + 
			"VALUES (:prm1,:prm2,:prm3,:prm4,:prm5,:prm6,:prm7,CURRENT TIMESTAMP,:prm8, 'S')";

	public static final String DEPOSITO_MOVIMENTO_UPDATE = "UPDATE DBPROD.MOVTO_FINCR_DEP SET CTPO_ACAO_MOVTO = :prm1, CCHEQ_DEVLC = :prm2, CBCO = :prm3, CAG_MOVTO = :prm4, ROBS_MOVTO_FINCR = :prm5, CCTA_MOVTO = :prm6, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm7 " + 
			"WHERE CDEP_IDTFD = :whr1";
	 
	public static final String DEPOSITO_CANCELAR = "UPDATE DBPROD.DEP_IDTFD SET CIND_DEP_CANCD = 'S', CIND_DEP_PRROG = 'N', DPRROG_DEP_IDTFD = NULL, CSIT_DEP_ARQ_TRNSF = :prm1, DCANCT_DEP_IDTFD = CURRENT TIMESTAMP, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :whr1 WHERE CDEP_IDTFD = :whr2"; 

	public static final String DEPOSITO_PRORROGAR = "UPDATE DBPROD.DEP_IDTFD SET CIND_DEP_PRROG = 'S', CIND_DEP_CANCD = 'N', DCANCT_DEP_IDTFD = NULL, CSIT_DEP_ARQ_TRNSF = :prm1, DPRROG_DEP_IDTFD = :prm2, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :whr1 WHERE CDEP_IDTFD = :whr2";

	public static final String DEPOSITO_UPDATE = "UPDATE DBPROD.DEP_IDTFD SET CINTRN_CIA_SEGDR = :prm1, CSIT_DEP_ARQ_TRNSF = :prm2, CDEPTO_DEP_IDTFD = :prm3, CMOTVO_DEP_IDTFD = :prm4, CBCO = :prm5, CAG_BCRIA = :prm6, CRAMO_SEGUR_SAP = :prm7, CCTA_CORR = :prm8, CSUCUR_EMISR = :prm9, NITEM_APOLC = :prm10, NPROT = :prm11, CTPO_DOCTO = :prm12, NAPOLC = :prm13, CPSSOA_DEPST = :prm14, CPROCS_JURID = :prm15, NBLETO_COBR = :prm16, NENDSS = :prm17, NPCELA_PRMIO = :prm19, CTPO_GRP_RECEB = :prm20, ROBS_DEP_IDTFD = :prm21, DVCTO_DEP_IDTFD = :prm22, VDEP_IDTFD_ORIGN = :prm23, DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = :prm24 , CRAMO_SEGUR = NULL WHERE CDEP_IDTFD = :prm25";

	public static final String DEPOSITO_UPDATELOGS = "UPDATE DBPROD.DEP_IDTFD SET DHORA_ULT_ATULZ = CURRENT TIMESTAMP, CUSUAR_RESP_ATULZ = ? WHERE CDEP_IDTFD = ?";

	public static final String DEPOSITO_INATIVAR = "UPDATE DBPROD.DEP_IDTFD SET DHORA_ULT_ATULZ = CURRENT TIMESTAMP,CUSUAR_RESP_ATULZ = ?,CIND_REG_ATIVO = 'N' " + 
			"WHERE CDEP_IDTFD = ? AND (CSIT_DEP_ARQ_TRNSF = 1 OR CSIT_DEP_ARQ_TRNSF = 4 OR CSIT_DEP_ARQ_TRNSF = 5)";

	public static final String DEPOSITO_INSERIRDV = "UPDATE DBPROD.DEP_IDTFD set CDIG_DEP_IDTFD = :prm1 where CDEP_IDTFD = :whr1";

	public static final String DEPOSITO_OBTERPORMOTIVO = "SELECT DBPROD.DEP_IDTFD.CDEP_IDTFD, DBPROD.DEP_IDTFD.CDIG_DEP_IDTFD, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CDEPTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CMOTVO_DEP_IDTFD, DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, COALESCE(LPAD(CAST(DBPROD.DEP_IDTFD.CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,DBPROD.DEP_IDTFD.CRAMO_SEGUR_SAP) as CRAMO_SEGUR, DBPROD.DEP_IDTFD.CSUCUR_EMISR, DBPROD.DEP_IDTFD.NITEM_APOLC, DBPROD.DEP_IDTFD.NPROT, DBPROD.DEP_IDTFD.CTPO_DOCTO, DBPROD.DEP_IDTFD.NAPOLC, DBPROD.DEP_IDTFD.CPSSOA_DEPST, DBPROD.DEP_IDTFD.CPROCS_JURID, DBPROD.DEP_IDTFD.NBLETO_COBR, DBPROD.DEP_IDTFD.NENDSS, DBPROD.DEP_IDTFD.NPCELA_PRMIO, DBPROD.DEP_IDTFD.CTPO_GRP_RECEB, DBPROD.DEP_IDTFD.ROBS_DEP_IDTFD, DBPROD.DEP_IDTFD.CIND_DEP_PRROG, DBPROD.DEP_IDTFD.DVCTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CIND_DEP_CANCD, DBPROD.DEP_IDTFD.DPRROG_DEP_IDTFD, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.DEP_IDTFD.DCANCT_DEP_IDTFD, DBPROD.DEP_IDTFD.DHORA_INCL_REG, DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEP_IDTFD.CIND_REG_ATIVO FROM DBPROD.DEP_IDTFD " + 
			"WHERE DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.DEP_IDTFD.CMOTVO_DEP_IDTFD = :whr1 and (CSIT_DEP_ARQ_TRNSF = 2 or CSIT_DEP_ARQ_TRNSF = 3 or CSIT_DEP_ARQ_TRNSF = 6)";

	public static final String DEPOSITO_OBTERPORDEPARTAMENTO = "SELECT DBPROD.DEP_IDTFD.CDEP_IDTFD, DBPROD.DEP_IDTFD.CDIG_DEP_IDTFD, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CDEPTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CMOTVO_DEP_IDTFD, DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, COALESCE(LPAD(CAST(DBPROD.DEP_IDTFD.CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,DBPROD.DEP_IDTFD.CRAMO_SEGUR_SAP) as CRAMO_SEGUR, DBPROD.DEP_IDTFD.CSUCUR_EMISR, DBPROD.DEP_IDTFD.NITEM_APOLC, DBPROD.DEP_IDTFD.NPROT, DBPROD.DEP_IDTFD.CTPO_DOCTO, DBPROD.DEP_IDTFD.NAPOLC, DBPROD.DEP_IDTFD.CPSSOA_DEPST, DBPROD.DEP_IDTFD.CPROCS_JURID, DBPROD.DEP_IDTFD.NBLETO_COBR, DBPROD.DEP_IDTFD.NENDSS, DBPROD.DEP_IDTFD.NPCELA_PRMIO, DBPROD.DEP_IDTFD.CTPO_GRP_RECEB, DBPROD.DEP_IDTFD.ROBS_DEP_IDTFD, DBPROD.DEP_IDTFD.CIND_DEP_PRROG, DBPROD.DEP_IDTFD.DVCTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CIND_DEP_CANCD, DBPROD.DEP_IDTFD.DPRROG_DEP_IDTFD, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.DEP_IDTFD.DCANCT_DEP_IDTFD, DBPROD.DEP_IDTFD.DHORA_INCL_REG, DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEP_IDTFD.CIND_REG_ATIVO FROM DBPROD.DEP_IDTFD " + 
			"WHERE DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.DEP_IDTFD.CDEPTO_DEP_IDTFD = :whr1 and (CSIT_DEP_ARQ_TRNSF = 2 or CSIT_DEP_ARQ_TRNSF = 3 or CSIT_DEP_ARQ_TRNSF = 6)";

	public static final String DEPOSITO_OBTERPORCONTACORRENTE = "SELECT DBPROD.DEP_IDTFD.CDEP_IDTFD, DBPROD.DEP_IDTFD.CDIG_DEP_IDTFD, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CDEPTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CMOTVO_DEP_IDTFD, DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, COALESCE(LPAD(CAST(DBPROD.DEP_IDTFD.CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,DBPROD.DEP_IDTFD.CRAMO_SEGUR_SAP) as CRAMO_SEGUR, DBPROD.DEP_IDTFD.CSUCUR_EMISR, DBPROD.DEP_IDTFD.NITEM_APOLC, DBPROD.DEP_IDTFD.NPROT, DBPROD.DEP_IDTFD.CTPO_DOCTO, DBPROD.DEP_IDTFD.NAPOLC, DBPROD.DEP_IDTFD.CPSSOA_DEPST, DBPROD.DEP_IDTFD.CPROCS_JURID, DBPROD.DEP_IDTFD.NBLETO_COBR, DBPROD.DEP_IDTFD.NENDSS, DBPROD.DEP_IDTFD.NPCELA_PRMIO, DBPROD.DEP_IDTFD.CTPO_GRP_RECEB, DBPROD.DEP_IDTFD.ROBS_DEP_IDTFD, DBPROD.DEP_IDTFD.CIND_DEP_PRROG, DBPROD.DEP_IDTFD.DVCTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CIND_DEP_CANCD, DBPROD.DEP_IDTFD.DPRROG_DEP_IDTFD, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.DEP_IDTFD.DCANCT_DEP_IDTFD, DBPROD.DEP_IDTFD.DHORA_INCL_REG, DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.DHORA_ULT_ATULZ, DBPROD.DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEP_IDTFD.CIND_REG_ATIVO FROM DBPROD.DEP_IDTFD " + 
	         "WHERE DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.DEP_IDTFD.CCTA_CORR = :whr1 AND DBPROD.DEP_IDTFD.CBCO = ? AND DBPROD.DEP_IDTFD.CAG_BCRIA = :whr2 and (CSIT_DEP_ARQ_TRNSF = 2 or CSIT_DEP_ARQ_TRNSF = 3 or CSIT_DEP_ARQ_TRNSF = 6)";

	public static final String DEPOSITO_OBTERSITUACAO = "SELECT CSIT_DEP_ARQ_TRNSF FROM DBPROD.DEP_IDTFD WHERE CDEP_IDTFD = :whr1";

	public static final String DEPOSITO_VERIFICARLANCAMENTO = "SELECT L_VTOT_DEP_IDTFD FROM DBPROD.DEP_IDTFD D, DBPROD.LCTO_DEP_IDTFD L WHERE D_CDEP_IDTFD = L_CDEP_IDTFD AND D_CDEP_IDTFD = :whr1"; 

	public static final String DEPOSITO_VERIFICARARQUIVOTRANSFERENCIA = "SELECT I_CITEM_ARQ_TRNSF, D_CSIT_DEP_ARQ_TRNSF FROM DBPROD.ITEM_ARQ_TRNSF I, DBPROD.DEP_IDTFD D WHERE I_CDEP_IDTFD = D_CDEP_IDTFD AND D_CDEP_IDTFD = :whr1"; 

	public static final String DEPOSITO_LOGS_INSERT = "INSERT INTO DBPROD.LOG_DEP_IDTFD (CDEP_IDTFD, RNOME_ATRIB_ALT, RCONTD_ANTIG, RCONTD_NOVO, CUSUAR_ATULZ_NOVO, CUSUAR_ATULZ_ANTIG, DHORA_INCL_REG) VALUES (:prm1, :prm2, :prm3, :prm4, :prm5, :prm6, CURRENT TIMESTAMP)";

	public static final String RELATORIOENVIORETORNO_OBTERDADOSANALITICO = "SELECT DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.CDIG_DEP_IDTFD, DBPROD.DEP_IDTFD.NBLETO_COBR, DBPROD.DEP_IDTFD.CSUCUR_EMISR, COALESCE(LPAD(CAST(DBPROD.DEP_IDTFD.CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,UPPER(DBPROD.DEP_IDTFD.CRAMO_SEGUR_SAP)) as CRAMO_SEGUR, DBPROD.DEP_IDTFD.NAPOLC, DBPROD.DEP_IDTFD.NITEM_APOLC, DBPROD.DEP_IDTFD.CTPO_DOCTO, DBPROD.DEP_IDTFD.NENDSS, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.NPCELA_PRMIO, DBPROD.DEP_IDTFD.CDEP_IDTFD,  DBPROD.DEP_IDTFD.CPSSOA_DEPST, DBPROD.DEP_IDTFD.DVCTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.LCTO_DEP_IDTFD.VTOT_DEP_IDTFD, DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR FROM DBPROD.DEP_IDTFD LEFT OUTER JOIN DBPROD.LCTO_DEP_IDTFD ON DBPROD.DEP_IDTFD.CDEP_IDTFD = DBPROD.LCTO_DEP_IDTFD.CDEP_IDTFD AND DBPROD.LCTO_DEP_IDTFD.CIND_REG_ATIVO = 'S'  " + 
			"WHERE ((DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF IN (2,3,5,6)) AND (DBPROD.DEP_IDTFD.DHORA_INCL_REG BETWEEN :dataInicio AND :dataFim )) AND DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' {0}  ORDER BY DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF"; 

	public static final String RELATORIOENVIORETORNO_OBTERDADOSSINTETICO = "SELECT DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.NBLETO_COBR, DBPROD.DEP_IDTFD.CSUCUR_EMISR, COALESCE(LPAD(CAST(DBPROD.DEP_IDTFD.CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,UPPER(DBPROD.DEP_IDTFD.CRAMO_SEGUR_SAP)) as CRAMO_SEGUR, DBPROD.DEP_IDTFD.NAPOLC, DBPROD.DEP_IDTFD.NITEM_APOLC, DBPROD.DEP_IDTFD.CTPO_GRP_RECEB, DBPROD.DEP_IDTFD.NENDSS, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.NPCELA_PRMIO, DBPROD.DEP_IDTFD.CDEP_IDTFD,  DBPROD.DEP_IDTFD.CPSSOA_DEPST, DBPROD.DEP_IDTFD.DVCTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.LCTO_DEP_IDTFD.VTOT_DEP_IDTFD, DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR FROM DBPROD.DEP_IDTFD  LEFT OUTER JOIN DBPROD.LCTO_DEP_IDTFD ON DBPROD.DEP_IDTFD.CDEP_IDTFD = DBPROD.LCTO_DEP_IDTFD.CDEP_IDTFD AND DBPROD.LCTO_DEP_IDTFD.CIND_REG_ATIVO = 'S' " + 
			"WHERE ((DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF IN (2,3,5,6)) AND (DBPROD.DEP_IDTFD.DHORA_INCL_REG BETWEEN :dtInicio AND :dtFim)) AND DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' {0}  ORDER BY DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF"; 

	public static final String RELATORIOMANUTENCOES_OBTERDADOSANALITICO = "SELECT DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.NBLETO_COBR, DBPROD.DEP_IDTFD.CDIG_DEP_IDTFD, DBPROD.DEP_IDTFD.CSUCUR_EMISR, COALESCE(LPAD(CAST(DBPROD.DEP_IDTFD.CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,DBPROD.DEP_IDTFD.CRAMO_SEGUR_SAP) as CRAMO_SEGUR, DBPROD.DEP_IDTFD.NAPOLC, DBPROD.DEP_IDTFD.NITEM_APOLC, DBPROD.DEP_IDTFD.CTPO_DOCTO, DBPROD.DEP_IDTFD.NENDSS, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.NPCELA_PRMIO, DBPROD.DEP_IDTFD.CDEP_IDTFD, DBPROD.DEP_IDTFD.CPSSOA_DEPST, DBPROD.DEP_IDTFD.DVCTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.LCTO_DEP_IDTFD.VTOT_DEP_IDTFD, DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, DBPROD.MOVTO_FINCR_DEP_CTPO_ACAO_MOVTO FROM DBPROD.MOVTO_FINCR_DEP, DBPROD.DEP_IDTFD LEFT OUTER JOIN DBPROD.LCTO_DEP_IDTFD ON DBPROD.DEP_IDTFD.CDEP_IDTFD = DBPROD.LCTO_DEP_IDTFD.CDEP_IDTFD AND DBPROD.LCTO_DEP_IDTFD.CIND_REG_ATIVO = 'S' " + 
			"WHERE DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.MOVTO_FINCR_DEP_CDEP_IDTFD = DBPROD.DEP_IDTFD.CDEP_IDTFD AND (DBPROD.MOVTO_FINCR_DEP_DHORA_ULT_ATULZ BETWEEN :whr1 AND :whr2) AND DBPROD.MOVTO_FINCR_DEP_CIND_REG_ATIVO = 'S' AND DBPROD.MOVTO_FINCR_DEP_CTPO_ACAO_MOVTO IN ('A', 'T', 'D', 'R') # ORDER BY DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, DBPROD.MOVTO_FINCR_DEP_CTPO_ACAO_MOVTO"; 

	public static final String RELATORIO_EXTRATO_SINTETICO = "SELECT DBPROD.DEP_IDTFD.CBCO,  DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR, DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.CDEP_IDTFD, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.LCTO_DEP_IDTFD.VTOT_DEP_IDTFD FROM DBPROD.DEP_IDTFD LEFT OUTER JOIN DBPROD.LCTO_DEP_IDTFD ON DBPROD.DEP_IDTFD.CDEP_IDTFD = DBPROD.LCTO_DEP_IDTFD.CDEP_IDTFD " + 
			"WHERE (DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF = 3 AND (DBPROD.LCTO_DEP_IDTFD. DHORA_INCL_REG BETWEEN :dtInicio AND :dtFim )) AND DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.LCTO_DEP_IDTFD.CIND_REG_ATIVO = 'S' # ORDER BY DBPROD.DEP_IDTFD.CBCO,  DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR"; 

	public static final String RELATORIO_EXTRATO_ANALITICO = "SELECT DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF, DBPROD.DEP_IDTFD.NBLETO_COBR, DBPROD.DEP_IDTFD.CSUCUR_EMISR, DBPROD.DEP_IDTFD.CDIG_DEP_IDTFD, COALESCE(LPAD(CAST(DBPROD.DEP_IDTFD.CRAMO_SEGUR AS VARCHAR(4)),4,'0') ,DBPROD.DEP_IDTFD.CRAMO_SEGUR_SAP) as CRAMO_SEGUR, DBPROD.DEP_IDTFD.NAPOLC, DBPROD.DEP_IDTFD.NITEM_APOLC, DBPROD.DEP_IDTFD.CTPO_DOCTO, DBPROD.DEP_IDTFD.NENDSS, DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.NPCELA_PRMIO, DBPROD.DEP_IDTFD.CDEP_IDTFD, DBPROD.DEP_IDTFD.CPSSOA_DEPST, DBPROD.DEP_IDTFD.DVCTO_DEP_IDTFD, DBPROD.DEP_IDTFD.CUSUAR_RESP_ATULZ, DBPROD.DEP_IDTFD.VDEP_IDTFD_ORIGN, DBPROD.LCTO_DEP_IDTFD.VTOT_DEP_IDTFD, DBPROD.DEP_IDTFD.CBCO, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR FROM DBPROD.DEP_IDTFD LEFT OUTER JOIN DBPROD.LCTO_DEP_IDTFD ON DBPROD.DEP_IDTFD.CDEP_IDTFD = DBPROD.LCTO_DEP_IDTFD.CDEP_IDTFD " + 
			"WHERE ((DBPROD.DEP_IDTFD.CSIT_DEP_ARQ_TRNSF = 3) AND (DBPROD.LCTO_DEP_IDTFD. DHORA_INCL_REG BETWEEN :dtInicio AND :dtFim)) AND DBPROD.DEP_IDTFD.CIND_REG_ATIVO = 'S' AND DBPROD.LCTO_DEP_IDTFD.CIND_REG_ATIVO = 'S' #  ORDER BY DBPROD.DEP_IDTFD.CBCO,  DBPROD.DEP_IDTFD.CINTRN_CIA_SEGDR, DBPROD.DEP_IDTFD.CAG_BCRIA, DBPROD.DEP_IDTFD.CCTA_CORR"; 

	public static final String RELATORIODADOSCOMPLEMENTARES_OBTERDADOSCOMPLEMENTARESANALITICO = "SELECT A_CDEP_IDTFD, A_CDIG_DEP_IDTFD, A_CBCO, A_CAG_BCRIA, A_CCTA_CORR, A_CTPO_GRP_RECEB, A_CSIT_DEP_ARQ_TRNSF, A_DHORA_INCL_REG AS DHORA_INCL_DEP, A_VDEP_IDTFD_ORIGN, B_DHORA_INCL_REG AS DHORA_INCL_LCTO, B_VTOT_DEP_IDTFD, C_CINTRN_CIA_SEGDR, C_CDEPTO_DEP_IDTFD, C_CMOTVO_DEP_IDTFD, C_ROBS_PARMZ_DEP, A_ROBS_DEP_IDTFD FROM DBPROD.PARMZ_DEP_IDTFD C, DBPROD.DEP_IDTFD A LEFT JOIN DBPROD.LCTO_DEP_IDTFD B ON A_CDEP_IDTFD = B_CDEP_IDTFD " + 
			"WHERE A_CSIT_DEP_ARQ_TRNSF = 3 AND ((A_DHORA_INCL_REG BETWEEN :dtIniciaA AND :dtFimA) OR (B_DHORA_INCL_REG BETWEEN :dtIniciaB AND :dtFimB)) AND (A_CINTRN_CIA_SEGDR = C_CINTRN_CIA_SEGDR AND A_CDEPTO_DEP_IDTFD = C_CDEPTO_DEP_IDTFD AND A_CMOTVO_DEP_IDTFD = C_CMOTVO_DEP_IDTFD) AND A_CIND_REG_ATIVO = 'S' AND C_CIND_REG_ATIVO = 'S' AND B_VTOT_DEP_IDTFD IS NOT NULL # ORDER BY CTPO_GRP_RECEB, CBCO, CINTRN_CIA_SEGDR, CAG_BCRIA, CCTA_CORR, CSIT_DEP_ARQ_TRNSF";
	 
	public static final String PARCELASPENDENTES_INSERIRDEPOSITOCOBRANCA = "INSERT INTO DBPROD.PCELA_COBR_DEP_IDTFD (CDEP_IDTFD, CPCELA_COBR, CIDTFD_PCELA_ORIGE, VPCELA_COBR, VIOF_PCELA_COBR, VRECBD_COBR, VIOF_RECBD, DVCTO_PCELA_COBR, DPGTO_COBR_BCO, DHORA_INCL_REG, CUSUAR_RESP_ATULZ, DHORA_ULT_ATULZ) " + 
			"VALUES (:prm1, :prm2, :prm3, :prm4, :prm5, :prm6, :prm7, :prm8, '01_01_0001', CURRENT TIMESTAMP, :prm9f , CURRENT TIMESTAMP)";

	public static final String PARCELASPENDENTES_LISTARPARCELASASSOCIADAS = "SELECT CPCELA_COBR FROM DBPROD.PCELA_COBR_DEP_IDTFD " +
			"WHERE CDEP_IDTFD = :whr1";

	public static final String PARCELASPENDENTES_DETALHARPARCELASASSOCIADAS = "SELECT CPCELA_COBR, CIDTFD_PCELA_ORIGE, VPCELA_COBR FROM DBPROD.PCELA_COBR_DEP_IDTFD " + 
			"WHERE CDEP_IDTFD = :whr1";

	public static final String PARCELASPENDENTES_EXCLUIRPARCELA = "DELETE FROM DBPROD.PCELA_COBR_DEP_IDTFD WHERE CDEP_IDTFD = whr1";
	
}
 
