package br.com.bradseg.depi.depositoidentificado.enums;

/**
 * Enum de paises
 * 
 * @author CPM Braxis Capgemini em 17 de ago de 2017
 */
public enum PaisEnum {
	
	BR("BR","Brasil"),
	AF("AF","Afeganistão"),
	ZA("ZA","África do Sul"),
	OR("OR","Alaranjado"),
	AL("AL","Albânia"),
	DE("DE","Alemanha"),
	AD("AD","Andorra"),
	AO("AO","Angola"),
	AI("AI","Anguilla"),
	AQ("AQ","Antártica"),
	AG("AG","Antígua e Barbuda"),
	SA("SA","Arábia Saudita"),
	DZ("DZ","Argélia"),
	AR("AR","Argentina"),
	AM("AM","Armênia"),
	AW("AW","Aruba"),
	AU("AU","Austrália"),
	AT("AT","Áustria"),
	AZ("AZ","Azerbaijão"),
	BL("BL","Azul"),
	BS("BS","Bahamas"),
	BD("BD","Bangladesh"),
	BB("BB","Barbados"),
	BH("BH","Barein"),
	BE("BE","Bélgica"),
	BZ("BZ","Belize"),
	BJ("BJ","Benin"),
	BM("BM","Bermudas"),
	BY("BY","Bielorrússia"),
	BO("BO","Bolívia"),
	BQ("BQ","Bonaire, Santo Eustáquio e Saba"),
	BA("BA","Bósnia-Herzegóvina"),
	BW("BW","Botsuana"),
	BN("BN","Brunei Darussalam"),
	BG("BG","Bulgária"),
	BF("BF","Burquina Faso"),
	BI("BI","Burundi"),
	BT("BT","Butão"),
	CV("CV","Cabo Verde"),
	CM("CM","Camarões"),
	KH("KH","Camboja"),
	CA("CA","Canadá"),
	QA("QA","Catar"),
	KZ("KZ","Cazaquistão"),
	TD("TD","Chade"),
	CL("CL","Chile"),
	CN("CN","China"),
	CY("CY","Chipre"),
	SG("SG","Cingapura"),
	CO("CO","Colômbia"),
	KM("KM","Comores"),
	CG("CG","Congo"),
	KP("KP","Coréia do Norte"),
	KR("KR","Coréia do Sul"),
	CI("CI","Costa do Marfim"),
	CR("CR","Costa Rica"),
	HR("HR","Croácia"),
	CU("CU","Cuba"),
	CW("CW","Curaçao"),
	DK("DK","Dinamarca"),
	DJ("DJ","Djibuti"),
	DM("DM","Dominica"),
	EG("EG","Egito"),
	SV("SV","El Salvador"),
	AE("AE","Emirados Árabes Unidos"),
	EC("EC","Equador"),
	ER("ER","Eritréia"),
	SK("SK","Eslováquia"),
	SI("SI","Eslovênia"),
	ES("ES","Espanha"),
	EE("EE","Estônia"),
	ET("ET","Etiópia"),
	US("US","EUA"),
	RU("RU","Federação Russa"),
	FJ("FJ","Fiji"),
	PH("PH","Filipinas"),
	FI("FI","Finlândia"),
	FR("FR","França"),
	GA("GA","Gabão"),
	GM("GM","Gâmbia"),
	GH("GH","Gana"),
	GE("GE","Geórgia"),
	GS("GS","Georgia do Sul e Ilhas Sandwich do Sul"),
	GI("GI","Gibraltar"),
	GD("GD","Granada"),
	GR("GR","Grécia"),
	GL("GL","Groenlândia"),
	GP("GP","Guadalupe"),
	GU("GU","Guam"),
	GT("GT","Guatemala"),
	GG("GG","Guernsey (ilha do Canal)"),
	GY("GY","Guiana"),
	GF("GF","Guiana francesa"),
	GN("GN","Guiné"),
	GW("GW","Guiné Bissau"),
	GQ("GQ","Guiné Equatorial"),
	HT("HT","Haiti"),
	HM("HM","Heard e Ilhas McDonald"),
	HN("HN","Honduras"),
	HK("HK","Hong Kong"),
	HU("HU","Hungria"),
	YE("YE","Iêmen"),
	CX("CX","Ilha Christmas"),
	CK("CK","Ilha Cook"),
	IM("IM","Ilha de Man"),
	NF("NF","Ilha Norfolk"),
	PN("PN","Ilha Pitcairn"),
	BV("BV","Ilhas Bouvet"),
	KY("KY","Ilhas Cayman"),
	CC("CC","Ilhas Coco"),
	FO("FO","Ilhas Faroé"),
	FK("FK","Ilhas Malvinas"),
	MH("MH","Ilhas Marshall"),
	UM("UM","Ilhas Menores dos EUA"),
	SB("SB","Ilhas Salomão"),
	TK("TK","Ilhas Toquelau"),
	TC("TC","Ilhas Turcas e Caicos"),
	VG("VG","Ilhas Virgens (Reino Unido)"),
	VI("VI","Ilhas Virgens Americanas"),
	IN("IN","Índia"),
	ID("ID","Indonésia"),
	IR("IR","Irã"),
	IQ("IQ","Iraque"),
	IE("IE","Irlanda"),
	IS("IS","Islândia"),
	IL("IL","Israel"),
	IT("IT","Itália"),
	JM("JM","Jamaica"),
	JP("JP","Japão"),
	JE("JE","Jérsei"),
	JO("JO","Jordânia"),
	KI("KI","Kiribati"),
	KW("KW","Kuaite"),
	LA("LA","Laos"),
	LS("LS","Lesoto"),
	LV("LV","Letônia"),
	LB("LB","Líbano"),
	LR("LR","Libéria"),
	LY("LY","Líbia"),
	LI("LI","Liechtenstein"),
	LT("LT","Lituânia"),
	LU("LU","Luxemburgo"),
	MO("MO","Macau"),
	MK("MK","Macedônia"),
	MG("MG","Madagascar"),
	MY("MY","Malásia"),
	MW("MW","Maláwi"),
	MV("MV","Maldivas"),
	ML("ML","Mali"),
	MT("MT","Malta"),
	MP("MP","Marianas do Norte"),
	MA("MA","Marrocos"),
	MQ("MQ","Martinica"),
	MU("MU","Maurício"),
	MR("MR","Mauritânia"),
	YT("YT","Mayotte"),
	MX("MX","México"),
	FM("FM","Micronésia"),
	MZ("MZ","Moçambique"),
	MD("MD","Moldova"),
	MC("MC","Mônaco"),
	MN("MN","Mongólia"),
	MS("MS","Montserrat"),
	MM("MM","Myanmar"),
	UN("UN","Nações Unidas"),
	NA("NA","Namíbia"),
	NR("NR","Nauru"),
	NP("NP","Nepal"),
	NI("NI","Nicarágua"),
	NE("NE","Níger"),
	NG("NG","Nigéria"),
	NU("NU","Niue"),
	NO("NO","Noruega"),
	NC("NC","Nova Caledônia"),
	NZ("NZ","Nova Zelândia"),
	OM("OM","Omã"),
	NT("NT","OTAN"),
	NL("NL","Países Baixos"),
	PW("PW","Palau"),
	PS("PS","Palestina"),
	PA("PA","Panamá"),
	PG("PG","Papua Nova Guiné"),
	PK("PK","Paquistão"),
	PY("PY","Paraguai"),
	PE("PE","Peru"),
	PF("PF","Polinésia Francesa"),
	PL("PL","Polônia"),
	PR("PR","Porto Rico"),
	PT("PT","Portugal"),
	KE("KE","Quênia"),
	KG("KG","Quirguistão"),
	GB("GB","Reino Unido"),
	CF("CF","República Centro-Africana"),
	CD("CD","República do Congo"),
	DO("DO","República Dominicana"),
	CZ("CZ","República Tcheca"),
	RE("RE","Reunião"),
	RO("RO","Romênia"),
	RW("RW","Ruanda"),
	EH("EH","Saara Ocidental"),
	AS("AS","Samoa Americana"),
	WS("WS","Samoa Ocidental"),
	SM("SM","San Marino"),
	SH("SH","Santa Helena"),
	LC("LC","Santa Lúcia"),
	KN("KN","São Cristóvão e Névis"),
	SX("SX","São Martinho (parte neerlandesa)"),
	PM("PM","São Pedro e Miquelon"),
	ST("ST","São Tomé e Príncipe"),
	VC("VC","São Vicente e Granadinas"),
	SC("SC","Seicheles"),
	SN("SN","Senegal"),
	SL("SL","Serra Leoa"),
	CS("CS","Sérvia e Montenegro"),
	SY("SY","Síria"),
	SO("SO","Somália"),
	LK("LK","Sri Lanka"),
	SZ("SZ","Suazilandia"),
	SD("SD","Sudão"),
	SS("SS","Sudão do Sul"),
	SE("SE","Suécia"),
	CH("CH","Suíça"),
	SR("SR","Suriname"),
	SJ("SJ","Svalbard"),
	TJ("TJ","Tadjiquistão"),
	TH("TH","Tailândia"),
	TW("TW","Taiwan"),
	TZ("TZ","Tanzânia"),
	TF("TF","Terras Austrais e Antárticas Francesas"),
	IO("IO","Território Britânico no Oceano Índico"),
	TL("TL","Timor Leste"),
	TP("TP","Timor Leste"),
	TG("TG","Togo"),
	TO("TO","Tonga"),
	TT("TT","Trinidad e Tobago"),
	TN("TN","Tunísia"),
	TM("TM","Turcomenistão"),
	TR("TR","Turquia"),
	TV("TV","Tuvalu"),
	UA("UA","Ucrânia"),
	UG("UG","Uganda"),
	EU("EU","União Européia"),
	UY("UY","Uruguai"),
	UZ("UZ","Uzbequistão"),
	VU("VU","Vanuato"),
	VA("VA","Vaticano"),
	VE("VE","Venezuela"),
	VN("VN","Vietnã"),
	WF("WF","Wallis e Futuna"),
	ZM("ZM","Zâmbia"),
	ZW("ZW","Zimbábue"),
	AX("AX","AX"),
	ME("ME","ME"),
	MF("MF","MF"),
	RS("RS","RS");

	private String codigo;
	private String descricao;

	PaisEnum(String codigo, String descricao) {
		this.codigo = codigo;
		this.descricao = descricao;
	}

	/**
	 * Retorna o atributo codigo.
	 * 
	 * @return Retorna o atributo codigo do tipo String.
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * Especifica o atributo codigo.
	 * 
	 * @param codigo String referente a codigo a ser setado.
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * Retorna o atributo descricao.
	 * 
	 * @return Retorna o atributo descricao do tipo String.
	 */
	public String getDescricao() {
		return descricao;
	}

	/**
	 * Especifica o atributo descricao.
	 * 
	 * @param descricao String referente a descricao a ser setado.
	 */
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
